### ISSUE TITLE
label all figure chunks

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#1]
This needs to be fixed, or as chapters grow we get errors of the wrong images showing up in the wrong place.

**Comment by trevorcampbell** [comment]
Is this still an issue? If so I'm happy to fix things given a bit more detail of what's wrong!

**Comment by ttimbers** [comment]
I am not sure if its 100% fixed... What we need to ensure is that every code chunk in the Rmd that generate figures need a name. Something like this (from 05-classification.Rmd) can potentially be really problematic...

<img width="588" alt="Screen Shot 2019-07-18 at 2 20 45 PM" src="https://user-images.githubusercontent.com/6865016/61492977-5be57200-a967-11e9-8109-c3c8ef688e0e.png">

Chunks like this should have a name. In the image below I give that chunk the name `howToClassify`. If we don't do this then RMarkdown makes names based on the chapter and chunk number (or something like that) and things can get mixed up...

<img width="580" alt="Screen Shot 2019-07-18 at 2 22 21 PM" src="https://user-images.githubusercontent.com/6865016/61493174-cb5b6180-a967-11e9-878a-33827228067e.png">

Looks like I wasn't aware, or very good at doing this... 😅 

<img width="747" alt="Screen Shot 2019-07-18 at 2 24 00 PM" src="https://user-images.githubusercontent.com/6865016/61493207-e0d08b80-a967-11e9-8948-d6356f99d450.png">

**Comment by trevorcampbell** [comment]
On it!

**Comment by trevorcampbell** [comment]
Fixed all. References now have chapter number prefix to avoid cross-chapter collisions, and only hyphens used per [the required style](https://bookdown.org/yihui/bookdown/figures.html)
