### ISSUE TITLE
Chapter 10 - teach named functions instead of anonymous functions?

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#100]
Students have a hard time with map and anonymous functions... Maybe we can teach named functions here and then just have them call that in `map`, so change `
map(k, ~kmeans(marketing_data, .x))` to:

```
marketing_kmeans <- function(k) {
    kmeans(marketing_data, k)
}

map(marketing_clust_ks, marketing_kmeans)
```

?

Another reason to do this is that named functions are just more generally useful than are anonymous ones...

**Comment by trevorcampbell** [comment]
Another plus is that this gives us an excuse to teach the students how to write their own function. I've noticed over the years that the stronger students figure this out for themselves and use them in their projects, but the weaker students don't and end up being limited by it.

**Comment by ttimbers** [comment]
I don't think we need this now with our move to using other `tidyverse` functions for the clustering chapter.
