### ISSUE TITLE
Review: Ch 1 (introduction) 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#101]
# Reviewer E: 
- Ch titles/subtitles: Section 1.4: “Assigning value to a data frame”. I would call this something like “assigning a data frame to a variable”. The use of the word “value” was confusing here because the data frame is the value being assigned and not the recipient of a value
    - TC: moot
- The table on types of analysis is split awkwardly across two pages. Since neither causal nor deterministic analysis is considered in the text, might it be better to cut these? 
    - TC: created a formatting issue for when we render latex
- I would strongly recommend loading individual packages instead of the `tidyverse` metapackage. Generally, it’s wasteful to load so many unneeded packages and dependencies, and for searching documentation it is helpful for student to know which precise package contains certain functions
    - TC: i vote we ignore this. for a beginner it's better to have a "one stop shop"
- Reproducibility could be motivated better. The text states that it is surprisingly difficult to recreate the exact same analysis, but students may not understand why anyone would want to do that exact same analysis again. 
    - ~**TC: todo**~ done
- I would move the explanation of fields of data from 1.5 to 1.3 before the initial csv is shown. It may be challenging for students to understand what is happening in the CSV without more intuition on the type of information encoded.
    - TC: moot
- When introducing dplyr::filter(), it would be useful to show examples with:
  - more than one condition
  - a condition created with something other than inequality operators (to emphasize it can be used with any vectorized function that returns TRUE/FALSE)
  - TC: not in this chapter! too soon
- I love the step-by-step development of ggplot, but the explanation is uneven. For example, the relatively simple xlab() and ylab() are explained explicitly but the more complex scales function is not. Consider more even coverage or alternatively mention how students can pull up the docs (with `?function_name`) to learn more
  - TC: first part about uneven explanation is moot
  - ~**TC: introduce ?function_name for docs??**~ done
- In 1.6.4: “the answer to both of these questions is no” -- I love the narrative here, but I think there could be more explanation of the why
  - TC: moot now
- When introducing dplyr::mutate()
  - This is such a critical function, perhaps it deserves its own section instead of being nestled inside of the data visualization section. This may be something students want to revisit, and currently it could be hard to find since it is masked in a data visualization section.
  - I found the mutate “template” [mutate(dataframe, column_to_create/transform = value/how_to_transform)] difficult to read because the slash made me think of division. I would just pick one of the two terms to put on each side.
  - TC: moot now

**Comment by trevorcampbell** [comment]
# Reviewer A
- "We have included a short demo video here". Confusing for a print edition. I suggest adding a link or some icon that is explained in the preface about where to find the videos and how to "read" the book.
- the linked video shows a different notebook than the one you link in the footnote of page 4
-

**Comment by ttimbers** [comment]
# Reviewer F
- Introduction chapter feels a bit rushed – it is at full speed for someone familiar with R but for a newbie.. subsetting may need a introduction – why this is needed at all. A link to tasks and problems oriented explanation would be useful.
- I am also quite puzzled that introduction seems to spread too widely as some topics are repeated in later chapters, e.g. ggplot and visualization chapter 
- Introduction: should include reference to libraries, the “function” example on p 6 assumes that tidyverse library is already installed. While JN can take care of this,students need to know about libraries and installing them in case they use RStudio.
- Chapters are quite “technical” and does assume some knowledge as well as “homework” preparation using other resources, suggested by the authors though.
- Chapters are filled with examples – which is fantastic, but some key knowledge is missing. E.g. visualization chapter just sends the reader to other textbook to read how to build visualizations and goes into details of what “effective visualizations are”. You can lose your reader in that “other” textbook and they never come back for the examples here.
- Machine learning principles need a chapter on its own (e.g. training/testing datasets, metrics and evaluation of models, bias/variance, etc.). Explaining the logic behind tidymodels also would be great – at this stage authors just “jump” into it. 
Introduction to statistical inference feels out of place, after Cluster analysis chapter it feels a bit too late….
- Appropriate, but datasets may need a bit more introduction. For the future – it may be good to stick with less datasets – to demonstrate how the same data can answer different questions.
- The book feels more like a reference manual or.. workshops materials… It is assumed that “theory” and foundations are covered somewhere else. Some fundamental knowledge and principles are missing – for example, Regression I: K-nearest neighbours section misses the explanation of the method and it is the first part of the regression method.. It just starts with a working example assuming that the readers “get” what the authors are referring to.
- The book is quite technical and does assume some experience. Could be a good reference book to “structure” and “organize” existing knowledge. Has too much “read this if you want more details” or “understand this”.  The content is “to the point” but can be hard to “digest” for newbies.
- Is the author’s approach to the subject appropriate for the intended level of the target audience? 
Well, for outstanding students in the cohort – it is a brilliant manuscript, but for the rest of the crowd (which may be the majority)…
- Good book, one of the best manuscripts in terms of concise coverage, organized flow and structure and care about Teaching&Learning process. However, the book has a common issue for textbooks – cover everything in the concise form.

**Comment by ttimbers** [comment]
# Reviewer C
- Third paragraph (after list of key data science problems we will solve): I don’t think this jargon will mean anything to the intended audience for the book - again, you’re writing for the acquisition editor rather than the intended reader.
- 1.3: There’s a _lot_ packed into this sentence - you do unpack it below, but readers are going to hit this paragraph first and be thrown.
- first time we load the tidyverse package: Please show readers the messages they’re likely to get when the load the tidvyerse - many think that the output means there’s an error.
- last paragraph of 1.3 (before the note): Not in black-and-white I can’t… :-/
- last note in 1.3: I think this is jargon that newcomers won’t understand
- second paragraph of 1.4: There’s a lot of jargon in these lines, and even without that, do newcomers really need to know about two kinds of assignment at this point?

**Comment by trevorcampbell** [comment]
- broken refs (e.g. in 1.1 theres a 11 - ??)

**Comment by trevorcampbell** [comment]
done per #218
