### ISSUE TITLE
Review: Ch 2 (reading) 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#102]
# Reviewer E: 
~- In 2.4.2: when mention data being read in with default names, it might be good to introduce base R names() or dplyr::rename()~
-~In 2.4.3: Long URL spills out of code box~
~- In 2.4.3.: “This is also demonstrated in the video below” -- consider adding conditional logic so this only shows up in the web version and not the PDF. Alternatively, since video content won’t be available to readers, consider if supplemental explanation is need~
- On databases:
  - ~“Thankfully, you don’t need to know SQL” may imply SQL is harder than it is. Consider rephrasing to not scare students off of something they will almost definitely need to know if they pursue data analysis!~
  - ~This section may require more motivation. Students may not be clear when or how they could encounter a database.~ 
  - ~It might be worth showing an example of dbplyr::show_query() just to illuminate how dbplyr works and why not all R functions work with it. Although students will not know SQL, showing this could illuminate that R is in fact translating every line of code to another language~
- On web scrapping:
  ~- In discussion of checking for legality of scraping, could mention R package {polite}~
  - ~Remove text on p. 45 clearly meant for class notes not book -- “this is optional not required reading” -- and consider how to supplement formerly video content~
  - I would seriously consider if this section is necessary. There are so many great APIs these days (and many wrapper R packages!), I think that is potentially a more useful skill. Additionally, an increasing number of pages use so much Javascript that {rvest} alone does not work and Selenium is required. 
     - *ML: I think we had a lot of discussion about this already and opted to include*
- ~p.44: just FYI on tiny tipo, double “is is”~

**Comment by leem44** [comment]
Reviewer B: 
- I very much like how Timbers gives students a taste of web scraping. Web-scraping is a practice that more and more students are encountering earlier and earlier in their careers, where as “back in my day” it wasn’t. In my experience, students get very excited when they can scrape tables off Wikipedia, imdb, and other popular websites.
- SQL!!! I always leave this as a throw-away topic at the end of my course and thus never cover it as well as I would like. Great to see how Timbers introduces it early.

**Comment by trevorcampbell** [comment]
# Reviewer D
- Reading in data locally and from the web -- “Locally” is a technical term – can it be replaced with “from your computer”

**Comment by trevorcampbell** [comment]
# Reviewer A
- page 25: Should readers have access to this (worksheet_02.ipynb)? If so, I think clearly stating this somewhere is key. I agree that knowing the difference between absolute and relative file paths is critical. It might be worth mentioning the `here` package somewhere, even if it's not used
- on p31, at the beginning or 2.4.3: I expected to see this discussion (of URLs) after relative vs. absolute file paths. Is it in the right spot here?
- Full URL doesn't fit on the page, consider using a URL shortener or posting the CSV in another location
- page 33: The video says you can click on the data to open it in the editor, but this doesn't match the text. Be sure to update the video before publication
- p35: "if the xlsx has multiple sheets..." Not much detail here, but a nice pointer. Are there exercises that help the reader explore this?
- p 39: The reader won't be able to connect to this DB, so warn them!
     - TC: we should just point them to a DB they *can* connect to...
- footnote on p43: This URL isn't sufficient
- top of p47 "In the case of this example node": It might be worth slowing down here and having the reader extract this string, then working through it before putting the pieces together. The html is too complicated.

**Comment by ttimbers** [comment]
# Reviewer C
- Overview: I’m finding this construction a bit awkward - can you introduce the term “tabular data” earlier (I think it’s more common)?
- section 2.3: I think this is misleading: there’s one location that is described by many paths. (If you say “the path is the place”, then it’s hard to explain multiple relative paths.)
- Fig 2.1: Tree diagrams of filesystems make sense to programmers, but I think most normal people are used to indented lists as shown in file browsers…
- udacity video link (Maybe put these into “further reading and viewing” at the end of the chapter for better findability?)
- section 2.4: "and here’s the term I’m looking for…" and "1. Have you explained the difference between these? 2. Is it important? 3. If it isn’t, can you use just one term??
- Note in section 2.4: OK, this is the explanation I ask for earlier… Can you please show some of the messages so they know what you’re referring to?
- section 2.4.1: I’m often asked at this point, “How can I tell how many lines to skip?” The answer is, “You have to read the file yourself and hard-code it,” but I think it needs to be said.
- section 2.4.2: Is this the right time to introduce this? I think it will confuse learners until they have more practice reading plain old CSV files…
- section 2.4.2: Do you think your intended learners will understand \t at this point? Escape characters haven’t been introduced and aren’t obvious…
- section 2.4.3: urlL > URL please (it’s an acronym)

**Comment by leem44** [comment]
these are all addressed
