### ISSUE TITLE
Review: Ch 5 (version_control) 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#105]
# Reviewer E: 
- comments in global issue

**Comment by leem44** [comment]
Reviewer B: 
- Chapter 5: On top of SQL and purrr, I think Chapter 5 serves as an excellent capstone to the “initially essential” topics basket.

**Comment by trevorcampbell** [comment]
# Reviewer D
- Move this chapter towards the end of the book

**Comment by trevorcampbell** [comment]
# Reviewer A
- p104: the mark holder quote should be at the beginning of the chapter before any text (TC: I agree)

**Comment by ttimbers** [comment]
# Reviewer C
- Section 5.3: I don’t know what value these lists have - if there’s a bit of description of the pros and cons, that would be more useful.
- Section 5.5: plaintext or “plain text”?
- Section 5.6: “What if I don’t have one of those?” asks the reader…
- Section 5.7.1: This is the specific example I requested above, but I doubt readers will still have the 5-point list in mind by the time they get here - it’s a lot to hold in memory.
-  Section 5.7.2: “For example?” asked the reader…
- Section 5.7.3: Again, I don’t think readers will have much luck following this without diagrams showing what files/commits are where, when.
- Section 5.8.2: I think there should be an explanation long before this point of why all this complexity is better than sharing files through Dropbox…
- Section 5.9.1: I was expecting a link to https://happygitwithr.com/ - I think it’s the most useful resource.
- Config. Manage. for the large... ref: I wouldn’t recommend this one any longer, especially not to beginners.

**Comment by leem44** [comment]
Typo in textbook 5.7.2: it is says "histry" instead of "history"

**Comment by ttimbers** [comment]
Not part of the review, but from teaching the course this term, I think we should add the learning objective below, and a corresponding section for it:

- checkout a past version of a file from the version control history

**Comment by ttimbers** [comment]
- redo screen shots with fake usernames

**Comment by trevorcampbell** [comment]
- this isn't for this chapter, but since the jupyter chapter is new we don't have anything for it. So i'll put it here to remind myself when i do the version control stuff. in the jupyter chapter, there's a typo at the end: `Untitle.ipynb` instead of `Untitled.ipynb`.

**Comment by trevorcampbell** [comment]
closed by #223
