### ISSUE TITLE
Review: Ch 9 (regression2) 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#109]
# Reviewer E: 
- [x] Great comparison of linear regression and KNN!
- [x] As in the classification section, I would continue to emphasize that there are so many more algorithms than what is described here

**Comment by leem44** [comment]
Reviewer B: 
- Nice treatment of descriptive (not inferential) linear regression given the limited allotment of ink/pages

**Comment by trevorcampbell** [comment]
# Reviewer D
- Can the authors clarify in the manuscript whether the tuning step of the workflow introduced in previous chapters is or is not necessary when performing linear regression?

**Comment by trevorcampbell** [comment]
# Reviewer A
- "multivariate" for regression could be confusing -- multiple predictors vs responses

**Comment by ttimbers** [comment]
Closed via #265
