### ISSUE TITLE
Review: Ch 10 (clustering)

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#110]
# Reviewer E: 

- [x] The dataset here is strange because “loyalty” and “satistfaction” are already the “latent” concepts and not things that feel directly measurable
- [x] As I describe in 3 (*see here: #103*), consider using summarize_*() variants instead of map_df()
- [ ] ~~Why is the elbow method done manually instead of in the tidymodels framework? Example here: https://www.tidymodels.org/learn/statistics/k-means/#clustering-in-r . It may be good to make students work to internalize formula but if so should at least highlight other option for long term~~
- [ ] Unsupervised learning is often quite hard in practice and may not always find meaningful results. It could be useful in this section especially to show an example of the method struggling or failing

**Comment by leem44** [comment]
Reviewer B: 
- Clustering by itself seems a little out of place, but I think more-than-zero exposure to unsupervised learning is called for. Again, I understand that book bloat is a thing, but if you were desperate for another unsupervised learning topic, a 2D principal components analysis is IMO accessible to undergrads, especially if you take a visual approach.

**Comment by trevorcampbell** [comment]
# Reviewer D
- When starting this chapter, a brief description of how Clustering differs from Classification would be helpful – for instance, with clustering we aim to identify “unknown labels” (corresponding to groups of observations falling into the same cluster) which we then interpret based on subject matter consideration whereas with Classification the labels are known a priori; with clustering we aim to assign new observations to one of the identified clusters (thereby inferring what “label” should be attached to them based on which cluster they are predicted to belong to) whereas with classification we aim to attach one of the known labels to the new observation.  
- Stating whether the input variables to be used in Clustering – as covered in the manuscript – should all be quantitative would be useful
- Can the authors clarify whether the workflow introduced for Classification would also be applicable to Clustering?

**Comment by trevorcampbell** [comment]
# Reviewer A
- Maybe add an objective about the difference between supervised and unsupervised learning
- In the figures in this chapter, I'd like to see better default colors here, maybe the colorblind friendly palette in ggthemes.
- p222: "uniformly randomly assigning" This could be more clearly stated for the novice. For example, "randomly assigning each observation to a cluster".
- p236 (re `~kmeans(...)`) You're using a different syntax now for anonymous functions. This is useful, but will confuse a novice since it isn't explained.
- p238: "We can help prevent..." Elaborate on what it does. How does it choose the best restart? Be a bit more verbose here.
-

**Comment by trevorcampbell** [comment]
- penguin data appears out of nowhere (would be good to dump into a csv and load using read_csv)

**Comment by ttimbers** [comment]
Reviewer E suggests this:

>  Why is the elbow method done manually instead of in the tidymodels framework? Example here: https://www.tidymodels.org/learn/statistics/k-means/#clustering-in-r . It may be good to make students work to internalize formula but if so should at least highlight other option for long term

However, in reviewing that link, from what I can tell, they do the same thing we do in our chapter (create the elbow method plot from a data frame that was created using `map` and using the `broom` functions), and so I am going to ignore this.

**Comment by ttimbers** [comment]
Reviewer B suggests this:

>  Clustering by itself seems a little out of place, but I think more-than-zero exposure to unsupervised learning is called for. Again, I understand that book bloat is a thing, but if you were desperate for another unsupervised learning topic, a 2D principal components analysis is IMO accessible to undergrads, especially if you take a visual approach.

I disagree - I think Kmeans is an accessible example of how to answer an exploratory question with a clustering approach. We also only give one example of one method in classification - KNN, which I think is also fine in such an introductory book. I think a 2D principal components analysis is IMO accessible to certain undergrads, but not our target audience, the ones I think that would work for would have a stronger math background.

What I can do is list some other examples of clustering, for example hierarchical clustering. And then add ISLR as an additional resource to explore this?

**Comment by trevorcampbell** [comment]
@ttimbers just add those examples in the additional resources section -- I don't know if i'd clutter the main chapter text with the intricacies of hierarchical clustering

**Comment by ttimbers** [comment]
Review E suggests:

> "Unsupervised learning is often quite hard in practice and may not always find meaningful results. It could be useful in this section especially to show an example of the method struggling or failing"

However, we are short on time. Thinking this could be good to add for version 2 of the book? @trevorcampbell @leem44 - are you two OK with that?

**Comment by ttimbers** [comment]
Closed via #250
