### ISSUE TITLE
Review: Ch 12 (moving-to-your-own-machine)

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#112]
# Reviewer E: 
- This might make sense earlier in the book. I would either move it to a Set-Up chapter or put it in an appendix which is referenced at the beginning. Otherwise, you might risk losing the book audience that doesn’t know how to get set up. 
- Nothing about the book requires JupyterHub so is this overly prescriptive? Someone could just as easily follow along with RStudio, Google Collab, or other platforms

**Comment by trevorcampbell** [comment]
# Reviewer A
- p.271 (re: "jupyter lab" split over two lines) It would be clearer not to have a line break here.
- p272 in the R packages block, You should also install the tidyverse here
- p272 You haven't discussed for loops before and now you are using them. This is going to confuse beginners without any explanation. (TC: I'm not sure what this refers to. Maybe we used a for loop somewhere else in the book and the reviewer's comment ended up here for some reason?)

# Trevor
- the bibliography is in really bad shape.
    - has some funny entries. e.g. "Canada, S. 2016"
    - bad/inconsistent capitalization
    - inconsistent journal / publisher / etc style
    - inconsistent inclusion of addresses / isbns etc
- the index is also silly. i'm not sure what generated this but it either needs to be fleshed out more (I would prefer that) or removed entirely.

**Comment by ttimbers** [comment]
@leem44 - did these all get addressed? If so, can you please close this?

**Comment by leem44** [comment]
Yes! I will make a new issue for the bibliography stuff
