### ISSUE TITLE
Move Jupyter-related content to System-setup chapter

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#118]
Rename "Moving to your own machine" to "System setup" (or something related? Like "Setting up your computer?"?) and move any Jupyter-related content there. We can then link to it from other chapters if needed. Bonus: can we also explain how to get setup and use Rmd with RStudio so our book can support both major DS literate code document platforms? Or at a minimum link out to other good resources on this (risk: they don't come back to us...). UI (how to use Jupyter & Rmd) stuff becomes videos with stable links. Make sure videos are general enough for the book, and not specific for this course. This addresses comments made by Rev C, E.  **MAJOR**

**Comment by ttimbers** [comment]
Branching off `dev` to `setting-up-your-computer` to work on this.

**Comment by ttimbers** [comment]
New chapter title: "Setting up your own computer"

New learning goals for this chapter:

By the end of the chapter, students will be able to:

- use Jupyter and RStudio to write, edit and run R code
- use Jupyter and RStudio version control tools for project versioning and 
collaboration
- install and run the software needed to write, edit and run R code shown in 
this book on their local computer (i.e., laptop)
- download files from JupyterHub and RStudio Cloud for local use (i.e, on
their own laptop)

@trevorcampbell @leem44 - what do you think of these?

**Comment by leem44** [comment]
Nice @ttimbers ! Looks good! For these two:
- use Jupyter and RStudio to write, edit and run R code
-  use Jupyter and RStudio version control tools for project versioning and collaboration

I don't think they are specific enough since they encompass a lot of things. I think it would be good if we spell out exactly what students are going to be learning (e.g. pull, push changes, handle conflicts etc) and these could be subtopics of these bigger overall learning objectives. 

I also think we have a lot of good content in Ch 5 which talks about the difference between git and github and why version control is necessary so we could add those as learning objectives as well

**Comment by trevorcampbell** [comment]
+1 to @leem44 's comments. I'll also suggest that we open an issue (now) to go through the textbook after everything is done to collect all the packages we use, and put them in this "setting up" chapter so students know what to install in advance.

**Comment by ttimbers** [comment]
There will be a separate chapter on version control that is more conceptual. So I think the learning objectives related to the difference between local and remote version control (git and github) and why version control is necessary will go there.

I do agree, that scoping the mechanical things they will learn in this chapter about version control could be further defined, so I could change them to:

- use Jupyter and RStudio version control tools for project versioning, specifically to:
  - commit changes to a local version control repository
  - push changes to a remote version control repository
  - resolve merge conflicts 
  - checkout a past version of a file from the version control history

**Comment by ttimbers** [comment]
Also, given that this chapter is about accessing R via server-solutions, how to use Jupyter and installing locally - I think system setup is not the best name...

I am thinking something more like: "How do I use R and version control?"

Also wondering if we want to split these off into two-three smaller chapters... At least separating the R/Jupyter mechanics from the version control mechanics seems like a good idea to me...

**Comment by ttimbers** [comment]
OK, fleshing this idea out a bit further, it becomes:

- Chapter 13: How to get started using R (server solutions & their UI's, how to use them)
- Chapter 14: How to get started using version control (intro to GitHubs' UI for creating repos, editing files, opening issues, using Jupyter & RStudio's version control tools/UI's to add, commit, push, pull, handle merge conflicts, checkout a file from the history)
- Chapter 15: Setting up your own system (how to install & setup R, Jupyter, RStudio and Git on your own laptop)

The reason for separating these is first, often we just want to point the students to one of these things. Second, having these 3 distinct things separate in the table of contents makes each of them more discoverable for the reader. And again, there is going to be a Chapter 12: Collaboration with version control, which will be more conceptual, and motivating. And will be expected to be read before the more tools-based version control chapter.
