### ISSUE TITLE
Revise supervised learning chapters

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#119]
- Add high-level sections to 6 (process - train & evaluate, 6 will cover train, 7 covers evaluate) & 8 (acknowledge that this is a repeat of 6 & 7 with a new flavour)
- add a wrap-up/summary at the end of 9 that brings everything together in context (we could introduce the term supervised learning, and hint that the next chapter covers a new type of analysis for a different problem, that is called unsupervised learning)
-  add some guidance on feature engineering at the end of the regression chapter
-  list other common algorithms in each chapter and even briefly mention when alternatives might be preferred
    
This will address comments made by Rev C & E. **MAJOR**

**Comment by trevorcampbell** [comment]
> we could introduce the term supervised learning, and hint that the next chapter covers a new type of analysis for a different problem, that is called unsupervised learning

I believe we already introduce supervised and unsupervised learning at the beginning of classification I if I recall correctly. As part of this change I'll figure out where that concept fits best.

Other common algorithms are now mentioend in the additional resources sections, but I think they pop up in the text as well. Will consider where that should be too.

**Comment by trevorcampbell** [comment]
made a branch `supervised-revision` for this

**Comment by trevorcampbell** [comment]
Copying some of the relevant review comments here for my convenience

> Before beginning modeling, I would like to see the book describe the model building process (data wrangling, picking an algorithm, tuning it with training data, evaluating it on test data, etc.) While all of the components are described, it may be hard for new readers to clearly separate out data, algorithms, parameters, and evaluation metrics without a framework. This could include some of the great content about evaluation that is currently in Chapter 7 but not specific to classification.
> 
> I think the book could benefit by discussing feature engineering. I see a common misconception with early-stage data scientists that they can simply model off of whatever fields happen to appear in their table. This leaves a lot of power on the table. Critically thinking about what features to include in a model is particularly important with algorithms like KNN (a focus of the book) for which performance can be significantly degraded with irrelevant predictors.. Additionally, this is a way to link the skills learned in the first and second halves of the book. .
> 
> While the book may not explain many different algorithms, could do more to acknowledge their existence. readers might come away thinking that classification is KNN, regression is linear modeling, clustering is K-means, and inference is comparison of means. It might be good to list other common algorithms in each chapter and even briefly mention when alternatives might be preferred.

**Comment by trevorcampbell** [comment]
Feature engineering, predictor selection, other common algorithms, and acknowledging similar material pattern all committed to the branch now. Still need to think about pre-summary and wrap-up...

**Comment by trevorcampbell** [comment]
this one is done after #146 was merged
