### ISSUE TITLE
Chapter 1-3Textbook Potential Fixes/Changes

### ISSUE THREAD

**Issue by Kingpin1111** [UBC-DSCI/introduction-to-datascience#12]
**Chapter 1 Notes and Potential Fixes to be made:**
- [x] Minor change to say that ‘the remaining chapters cover solution…’ instead of exactly 4 chapters.
- [x] **1.3**, In the introductory paragraph, maybe show a picture of what a spreadsheet looks like.
- [x] **1.3**, small typo/grammatical error in “..we are going to use read_csv() .. because it is fast it creates a special…”. 
- maybe "... because it is fast and creates.." instead
- [x] **1.3**, small typo “Next we call the read_csv() and pass it a single argument...” should state that read_csv() is a function. 
- maybe we should specify that these are functions and they accept arguments using read_csv() as an example
- [x] **1.3**, “.. default arguments are not appropriate, for example…”
- [x] **1.5**, “When peak…”
- "When peaking/glancing/printing..."
- [ ] ~~**1.5.3** For the logical operator argument for filter(), perhaps give a quick rundown/list of the types of logical operators there are.~~ not needed as I now have three examples in this chapter (one of `==`, `>` and one of `!=`
- [ ] ~~**1.6.2**, in the multiple pipe example, include a brief reason for good formatting lines of code when ‘piped’ together/in general.~~ not needed now as pipe was moved to chapter 3
- [x] **1.7.4**, “..loading the dataset to creating a visulazation …”
- "... visualization..."
- [ ] ~~**1.7.4** “”... resultant dataframe to left_join …”~~
- ~~left_join()*~~ not needed now as this has been removed - we just give the students the joined dataset~~

**Chapter 2 Notes: (a: problem, b: suggested solution)**
- [x] **2.3**
- a:  “... load in a dataset a plain text file…”
- b: “... load in a dataset from a plain text file…”
- a: “Whereas an absolute path…”
- b: Starting off in whereas seems unnecessary.“An absolute path…”
- [x] **2.4.1**
- a: “...use the read_delim function() instead..”
- b: Round brackets on the wrong function. “... read_delim() function instead..”

- **3.3.2**
- ~~a: possibly talk about how to access all elements within a vector~~
- ~~b: the '$' symbol can access an object's elements within a vector.~~
- [x] **3.5.2**
- a: 'Factorization' is mentioned without context
- b: either: include a resource talking about factorization, or say that it is unnecessary to understand within this course.
- [x] **3.5.3**
- a: "... the we read in data below..."
- b: "--- the data we read in below..."
- a: '... format is not idead...'
- b: '...format is not ideal...'
- [x] **3.6**
- a: the whole idea around adding arguments to the functions we want to make could be a separate sub-chapter to 3.6. 
- b: add the subsection to distinguish from 'using purrr's map* functions to iterate'
- [x]  **3.6.1**
- a: the section seems a bit short if you're just talking about map functions.
- b: combine it with the additional readings/resources to allow students to further discover map* potential.

Potential Q+A: What is the difference between ‘%>%’ and ‘+’ as operators/symbols between functions? 
Pipe-operator passes ‘values’ to other functions while the + operator adds layers to plots.

**Clarifier:** I recall having my classmates and I had a lot of confusion when learning the 'gather' function, and I have a good way of explaining it: "You create two new column names, and you choose which columns (we previously had) to map their column name as a 'key', and their observations as 'values' ".

**Comment by trevorcampbell** [comment]
all handled now in #26
