### ISSUE TITLE
Fix/improve index

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#120]
We need a robust index for this book. Check whether this can be autogenerated by `bookdown`? Talk to Laura (CRC Press) for help on this if we need to? Also, once we create the index, we want to create a glossary of the main terms and functions. Let's consider using the [`glossario` R package](https://github.com/carpentries/glosario) for this, and borrowing from the [Carpentries English glossary](https://glosario.carpentries.org/en/)? This addresses comments made by Rev E.  **MINOR/MAJOR?**

**Comment by trevorcampbell** [comment]
For generating an index: https://github.com/rstudio/bookdown/issues/149

**Comment by trevorcampbell** [comment]
After doing some brief exploration -- there is no good way to automate this, and it's going to take a lot of work. It's definitely a **MAJOR**.

Planning to do this last after all of the other big content revisions

**Comment by trevorcampbell** [comment]
Created the `index_glossary` branch for this work

**Comment by trevorcampbell** [comment]
this is being handled in the `makeindex` branch and #238
