### ISSUE TITLE
Summaries of where we are going

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#122]
Read through the book, and ensure there is a summary of where we are going for each walkthrough example in the book (especially 6, 7, 8). This will address comments made by Rev D. **MINOR/MAJOR**

**Comment by trevorcampbell** [comment]
@ttimbers I think we can close this one now, as it's fairly stale / based on the pre-review copy. If you agree feel free to close.

**Comment by trevorcampbell** [comment]
Closing; can re-open if needed.
