### ISSUE TITLE
Clarify examples from the the universe of possibilities

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#123]
Read through the book, and clarify where what we are discussing is meant to illustrate an example versus the universe of possibilities -- worth being more specific about things that are just high-level examples (e.g. KNN versus all classification algorithms). *For example, make it clear what parts of chapter 7 are relevant to classification in general, and which are relevant to just k-nn* **MINOR/MAJOR**

**Comment by trevorcampbell** [comment]
@ttimbers I think we can close this one now, as it's fairly stale / based on the pre-review copy

**Comment by trevorcampbell** [comment]
Closing; can re-open if needed.
