### ISSUE TITLE
Improve additional resources sections

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#126]
Add a few sentences to give context to each additional resource we share. This means going just beyond annotating them (we should also do that), but also explain what topic they should focus on next. Rebut: We will not add a where to go from here chapter, asked by reviewer ?, but will instead do better job at the end of each chapter, on a topic-by-topic basis.
MINOR

**Comment by ttimbers** [comment]
Make the citation formats consistent

**Comment by trevorcampbell** [comment]
Created the `additional_resources` branch for this work.

**Comment by trevorcampbell** [comment]
leaving a TODO note for me: make sure the classification chapters mention logistic regression in the additional resources. One of the edits for #129 requires this.

**Comment by trevorcampbell** [comment]
Done!
