### ISSUE TITLE
Improve regression introduction

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#129]
Lead into regression more gentle and rely less on past knowledge about classification (8.3 is a bit bizarre, should combine with 8.4). This will address comments made by Rev C.  **MINOR**

**Comment by trevorcampbell** [comment]
Created the `regression_intro_improvement` branch for this work

**Comment by trevorcampbell** [comment]
Rev C's specific comment

> Regression I: K-nearest neighbours section misses the explanation of the method and it is the first part of the regression method.. It just starts with a working example assuming that the readers “get” what the authors are referring to.

**Comment by trevorcampbell** [comment]
closed by #135
