### ISSUE TITLE
Chapter 6-11 Textbook Potential Fixes/Changes

### ISSUE THREAD

**Issue by sam-ip** [UBC-DSCI/introduction-to-datascience#13]
### **Potential Fixes to be made (a: problem, b: proposed solution)**
- [x]  **6.2**
- a: "... length of the ordinary, straight (Euclidean) distance line..."
- b: "... straight-line (Euclidean) distance..."
- [ ] **6.4.1.1**
- a: the column variable descriptions in the data-frame are placed without much context.
- b: The list could be fully removed as it is easy to read each column name in the glimpse() example.
- [x] **6.4.4**
- a: "... use k-nearest neighbours classifier..."
- b: "... use **the** k-nearest neighbours...."

- [x] **7.3**
- a: "...our classifier?"
- b: "... our classifier is?"
- [x]  **7.3.1.1**
- a: "... we set p = 0.75 when we called createDataPartition."
- b: "... we set p = 0.75 from calling createDataPartition."
- [x] **7.3.1.4**
- a: "... create vector..."
- b: "... create a vector..."
- [x] **7.4**
- a: "... the computation it takes..."
- b: "-- the more computation it takes..."
- [x] **7.6**
- a: "... really well... then our classification model..."
- b: "... really well... our classification..."
- a: "... when add more information..."
- b: "... when adding more information..."
- a: "... as though now will..."
- b: "... as though now with..."
- [x] **7.8**
- a: "... scale the data the ..."
- b: "... scale the data, the..."
- a: "... start doing and analysis..."
- b: "... start doing an analysis..."
- [ ] **8.1**
- a: Mentioning of words "response/explanatory variable with no prior knowledge of what they are
- b: Include small explanations for the target/response variables with the reasoning that they are dependent variables that we are finding the 'response' of. Likewise, another reason for explanatory. 
- [x] **8.4**
- a: "... Let's now visaulize..."
- b: "... Let's now visualize..."
- [ ] **8.4**
- a: "... as house size... increases, so does house price... we can reason that house size might be a useful predictor.
- b: Again, another example of learning how and what is/are good inferences to use for assumptions on data. In this example, this could be an example of how a positive correlation in variables may/can be a sign of a good predictor. (**MY IDEA**: Include a case where positive correlation may **not** be a sign of a good predictor)
- [x] **8.6**
- a: "... formula for calculation RMSE is shown below..."
- b: "... formula for calculating RMSE..."
- a: The second code block says that the column of k's is incrementing in 10's
- b: It should say that it is incrementing from 1 to 500 in increments of 5
- [ ] **8.6**
- a: "Here we see that the smallest  RMSE is from the model where k = 51"
- b: It is not entirely visible from the model. Perhaps a code block explaining how to extract the smallest RMSE by choosing the min(RMSE) from the results would be useful.
- [x] **8.8**
- a: "... Sacremento..."
- b: "... Sacramento..."
- [x] **9.3**
- a: "... separate terms exists..."
- b: "... separate terms exist..."
-  [x] **9.4**
- a: "... the only the other type of regression, there are..."
- b: "... the only type of regression. There are..."
- [x] **9.5**
- a: We do not need to perform cross-validation on linear regression, but creating a test data set is necessary.
- b: I myself, do not know why it is unnecessary to perform cross-validation on the data in the context of linear regression. The only reason I could think of this would be the reason that linear regression takes the average vertical distance of all points, so it would be unnecessary to cross-validate if all data points are taken into consideration for the algorithm.
- [x] **9.6**
- a: "... instead someother shape..."
- b: "... instead some other shape..."
- [x] **10.3**
- a: "... as in k-nn classification, in k-nn regression predictions..."
- b: "... as in k-nn classification and regression predictions..."
- a: The code block under "10-fold cross-validation" has an incorrect comment similar to the problem in **8.6**
- b: The same solution as **8.6** should be implemented
- a: "... of ~ 0.52 a scaled number..."
- b: "... of ~ 0.52 and a scaled number..."
- [x] **11.6**
- a: "...squares for differnt K's..."
- b: "...squares for different K's..."
- [x] **11.6**
**HELP!**
I do not understand the code block when forming the object marketing_clust_ks. Specifically, the part where we map the kmeans function on k. **MY GUESS:** the "~" is saying to perform kmeans in ".x" dimensions, which is the previous argument's "amount".

**IDEAS**: 
- For a ch. 6/7 test question, we could ask the full process of what training a knn-classification model with cross-validation and multiple choice k's is really doing behind the code. 
(My proposed answer would be along the lines that we first split into training/validation/testing sets and split the classifying variable(s) into training/testing sets.
We then train our training model for multiple values of k while cross-validating to regularize and decrease bias for our final model. We then find the best/smallest k-value which yields the highest accuracy for our model.)
- At the end of the sections talking about strengths and limitations, we should talk about how knn-classification is one classification algorithm of many, and perhaps talk about a faster/suitable algorithm that would work depending on the size of a data set. **Run-time of algorithms are discussed in CPSC221 for further information**
- perhaps include an additional reading (at the bottom of lecture notes) for complexity and suitability of classifications https://developers.google.com/machine-learning/crash-course/classification/video-lecture on google for further information about classification.)

### **Quiz Question(s)?**
- Give your own definition of supervised and unsupervised learning, and provide examples of both? 
- Of the following algorithms we have learned throughout the course, label each of them as a supervised/unsupervised learning method (or both!).
- What is the descriptor "bias"/"variance" and what does it mean to have a low/high bias/variance in our model? Which algorithms in the course would we use these descriptors as a measure of accuracy?

**Comment by trevorcampbell** [comment]
(changes made so far in the cleanup branch)

**Comment by Kingpin1111** [comment]
Found out **11.6** and the logic behind it. It is notation to create a function with "~" and the ".x" is replacing the variable output from the function.

**Comment by ttimbers** [comment]
Did the changes for this ever get merged @trevorcampbell ?

**Comment by sam-ip** [comment]
Just looking at the first two proposed changes, my proposed changes are either removed entirely or changed. It looks like there are no more subsections as I have labeled in the textbook no more.

I think the issue can be closed.
