### ISSUE TITLE
All figures need figure captions

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#152]
Aall figures need figure captions. @trevorcampbell - I think the PR you merged today on the reading chapter had some of these missing? For png's, I suggest we use `image_read` and `image_crop` from the `magick` package. I like this because I can then use R to crop my png's. I have used this for the book for the version control and Jupyter chapters.

Here's an example:

```
image_read("img/code-cell-not-run.png") %>% 
  image_crop("3632x1000")
```

**Comment by trevorcampbell** [comment]
added to style guide
