### ISSUE TITLE
Audio Quality

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#16]
The audio quality on the videos could be improved. I have a reasonably good microphone (AT2020) we could use for this. @ttimbers do you still have the original video / audio recording files somewhere?

Not high priority but figured I'd add an issue for whenever we are putting a final polish on things.

**Comment by ttimbers** [comment]
I think a re-record of the screencasts could be done and I'm happy to do then. Would love to borrow the microphone (and not be sick) when recording.

**Comment by trevorcampbell** [comment]
I'll bring my microphone in some time soon for you to borrow!

**Comment by trevorcampbell** [comment]
I don't believe we include videos directly any more; closing
