### ISSUE TITLE
including multiclass classification in Classification I

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#163]
@ttimbers suggested this in the review of PR #146 . I thought it would be worth a separate discussion.

I would like to include it, but it would require us to do one of:

- have multiple datasets in this chapter (because the one we have is no good for multiclass)
- rewrite the chapter for a dataset where multiclass is doable
- put a paragraph at the end (or somewhere else) without actually exploring it at all

I think the only feasible one of these to do is the third.

**Comment by ttimbers** [comment]
Moving this to #251 and closing.
