### ISSUE TITLE
Subsection headings vs bolding

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#164]
Unresolved comment from PR #146

We have noticed a few problems in the text related to subsection heading consistency

- In a bunch of places (especially predictive modelling chapters), we use bold to separate chunks of text. This looks good in HTML but may cause problems in PDF
- in places we nest a 4th level heading under a 2nd level heading (or just generally, don't follow the pattern of n+1 level under n level). This renders poorly in both HTML and PDF and makes the structure of the document hard to understand.

Is there an unnumbered subsection heading in Rmd? that would be the ideal solution

alternatively we can replace the bolds with \paragraph in latex and leave them as-is in HTML, and switch the 4th level subsection headings under 2nd levels to just be the bold + \paragraph too

**Comment by ttimbers** [comment]
We can control what headers end up in the TOC by setting `toc_depth` in the YAML frontmatter:

```
bookdown::gitbook:
    toc_depth: 2
```
We can choose 2, or 3, or whatever number we think is best for our book. If we do this, we can still link to level 3 & 4 headers where needed, but not have them numbered or show up in the TOC.

Docs: https://bookdown.org/yihui/rmarkdown/html-document.html#table-of-contents

**Comment by trevorcampbell** [comment]
I don't know... in some places we may want to have 3rd level stuff show up, in others not. Is there a way to set the TOC depth per chapter?

Either way, I think the best overall solution would be unnumbered headings -- do they exist in Rmd? They do in latex.

**Comment by ttimbers** [comment]
There is also `{-}` that you can add on the same line as the header to have it omitted from the numbering. See: https://bookdown.org/yihui/rmarkdown-cookbook/unnumbered-sections.html

**Comment by trevorcampbell** [comment]
added this info to style guide
