### ISSUE TITLE
response / target / explanatory variable / predictor variable / feature / label

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#165]
We should make sure our usage of these terms is consistent throughout.

Should do this as part of specific chapter formatting.

**Comment by leem44** [comment]
Adding this comment here for classification1 chapter from (since comment box will depend on the terminology we go with in the rest of the text) #92 
> We call the X's in this chapter features, predictors and explanatory variables. We should just pick one and stick with it.
Agreed, but when we first introduce the term we should put in a comment box the synonyms that people commonly use

**Comment by trevorcampbell** [comment]
added to style guide
