### ISSUE TITLE
set.seed once at beginning of each chapter when loading packages

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#168]
currently we set seeds throughout chapters in kind of a haphazard way. Probably should just set the seed once at the beginning of each chapter. We also have a few "note" boxes throughout about seeds, should edit those once seed moved to beginning of chp.

**Comment by trevorcampbell** [comment]
also when you do this make sure the rest of the chapter doesn't break (figures still look good, conclusions about results still make sense)

**Comment by trevorcampbell** [comment]
After my most recent pass through the book, we really really should just make sure to `set.seed` *once* at the beginning of each chapter, and include a note box about it. 

Currently the note boxes are super confusing -- they say we `set.seed` to ensure reproducibility, which implies to students that they have to use `set.seed` everywhere to have reproducible code (this is quite problematic). The boxes also say that we `set.seed` to get the same results each time, and that if we didn't do it we wouldn't get the same result. But again this implies that students have to use `set.seed` all over the place instead of just once at the beginning (as they should).

I feel pretty strongly that we should `set.seed` once per chapter and give a very good description of what this is and why we do it (at least the first time, and then perhaps a short note referring back to the full explanation each time we do it afterward).

@ttimbers @leem44 tagging for visibility

**Comment by leem44** [comment]
@trevorcampbell Yes, I agree with this! In the inference chapter, we do different random samples so we will need `set.seed` in different places, but other than that I think we should only set it once at the start.

**Comment by ttimbers** [comment]
I think I wrote this somewhere else - but I agree with this approach in the book, in the worksheets we have to use a different approach since they can re-run the Jupyter cells many times. And if the seed is not set in that same cell, then the autograder will fail many of those times...

**Comment by trevorcampbell** [comment]
yes -- this suggestion is just for the book. In the worksheets we should tell the students why we set seed everywhere constantly (though I recall we already do this in one of the early worksheets)

**Comment by trevorcampbell** [comment]
Need to make sure we fix this before CRC subm
