### ISSUE TITLE
ch 4 organization changes

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#170]
Moving Tiffany's comments from #150 

> Also, a couple big picture things I think we need to be changed for this chapter (which maybe should be added to an issue specifically for this chapter, instead of this global issue PR) include:
> 
> 1. I think the organization of plotting stories should be grouped under plot types, we currently bounce back and forth between scatter and bar charts... Let's do line charts, then scatter, then bar charts? (or we could swap bar charts for scatter, either would be fine with me).
> 2. The grey background on the plots is not great. Can we teach them the use `theme` to remove it and have a plot with a white background?
> 3. Should we teach densities here? We use them in one worksheet/tutorial in the course but there is currently nothing about them here...

**Comment by ttimbers** [comment]
I think number 1 was addressed, and I don't feel as strongly about 2 & 3 anymore. I think they are too advanced for our students to worry about.
