### ISSUE TITLE
make sure plots follow ch 4 viz principles

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#172]
We probably want to go through the book and look at all of the graphs we make to make sure that they follow the visualization principles that we outline in Ch 4. e.g. size of labels, using default ggplot axes as suggested by Tiffany (linked below) etc 

https://github.com/UBC-DSCI/introduction-to-datascience/pull/150#discussion_r638448856

> From what I have read about data visualization (see: https://clauswilke.com/dataviz/proportional-ink.html#visualizations-along-linear-axes), we often do not want to start our axes where `ggplot`'s default puts them, as it inflates differences. We should address this here and show them how to change the axes to force them to start from 0.

**Comment by trevorcampbell** [comment]
added to style guide
