### ISSUE TITLE
feedback need on ch 1 example

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#177]
As per Tiffany's comment: 
This is a much better introduction to the chapter's problem 🎉 After we get this PR merged - let's work to get some feedback on it from someone from an Indigenous background? I think their insight into being respectful here would be very helpful. Let's open an issue to remind us to do this?

_Originally posted by @ttimbers in https://github.com/UBC-DSCI/introduction-to-datascience/pull/143#discussion_r642788831_

**Comment by leem44** [comment]
We still haven't done this -- leaving open

**Comment by trevorcampbell** [comment]
2 years later, still hasn't happened. Closing b/c unlikely anyone has capacity to do this. Feel free to re-open if you plan to do it
