### ISSUE TITLE
Mechanistic question in Ch 1

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#179]
As per Tiffany's comment below: 

I am now a bit worried about this example question - because we are asking about a mechanism, it reads as though we think it is true... Let's brainstorm another...

_Originally posted by @ttimbers in https://github.com/UBC-DSCI/introduction-to-datascience/pull/143#discussion_r642786101_

**Comment by leem44** [comment]
@ttimbers I don't think we addressed this yet eh? leave open?

**Comment by trevorcampbell** [comment]
All the Qs in ch1 seem good to me now -- and it's been a while since this was raised. It's likely stale now. Closing, can reopen if needed.
