### ISSUE TITLE
Notes underneath the text should be consistent in style

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#181]
The notes under text have inconsistent styling 
e.g.
From chapter 1: 

> **In case you want to know more (optional):** 
> There is another function, which also loads csv files called `read.csv`, which is a *base* R function, so we don't need to load a package to use it. Why are we using `read_csv` instead of `read.csv`? We use the `read_csv` function from the `tidyverse` because it's faster, and it has other advantages, such as a more readable format when printing the data frame. Therefore we will use `read_csv` from here on out. 

but then the **In case you want to know more** is not used consistently. I think we need to go through and just make them all consistent

**Comment by trevorcampbell** [comment]
added to style guide
