### ISSUE TITLE
Messages from `tidyverse` and `read_csv` in ch 1 & 2

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#188]
As mentioned by Reviewer C in Ch 2 review, the messages for the `tidyverse` and `read_csv` functions don't show up when textbook is rendered. 
- Note in section 2.4: OK, this is the explanation I ask for earlier… Can you please show some of the messages so they know what you’re referring to?

_Originally posted by @ttimbers in https://github.com/UBC-DSCI/introduction-to-datascience/issues/102#issuecomment-809713554_

**Comment by trevorcampbell** [comment]
@leem44 I believe this is handled now. Feel free to re-open if not.
