### ISSUE TITLE
videos in chapter 2 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#189]
Just flagging a comment from Reviewer A about chapter 2 video so we don't miss it: 
- page 33: The video says you can click on the data to open it in the editor, but this doesn't match the text. Be sure to update the video before publication

_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/issues/102#issuecomment-808957676_

**Comment by trevorcampbell** [comment]
@leem44 are these videos still there?

**Comment by leem44** [comment]
I think I removed them and added them as links in the additional resources section, but we may want to check the rest of the book. Dont know if the jupyter or version control chapters have them...

**Comment by leem44** [comment]
Also I realize the links to videos are not displayed so we should fix that since people obviously can't click on the links in a book. For Ch 2 and elsewhere.

**Comment by trevorcampbell** [comment]
I will add something about making sure links work in both HTML and PDF to the style guide.
