### ISSUE TITLE
Offline access

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#192]
From my peer evaluation last year -- the committee noted that it might be helpful to give students obvious means to obtain offline copies of the text. I know there's a "download as PDF" button that R bookdown creates, but currently it generates a 404 error. Probably a good idea (after our big current revision as of Jun 2021) to see if we can make this button work properly.

**Comment by ttimbers** [comment]
I agree it would be nice, but we agreed with CRC a press that we wouldn't do that (as they will sell a PDF version of the book in addition to the hard copy).

**Comment by trevorcampbell** [comment]
Good point. Aside from that, is there a way to make the HTML version downloadable? I mean they could always just open this repo and build the book themselves I guess, but that definitely won't be possible for the majority of the students.

**Comment by ttimbers** [comment]
They could download the repo as zip and then open `index.html` in the
`_book` directory.

**Comment by trevorcampbell** [comment]
Good idea. We might want to leave an instruction at the top of the README in this repo instructing people how to do that.

**Comment by trevorcampbell** [comment]
I'm going to close this; I think for the general student having an always available online copy + CRC press hardcopy is fine.
