### ISSUE TITLE
remove `map` in favour of summarize + across in wrangling (ch 3)? 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#193]
@ttimbers @trevorcampbell 

Many of the reviewers suggest cutting `purrr`'s `map` in favour of something simpler (`summarize` and `across` was a suggestion) as mentioned here: https://github.com/UBC-DSCI/introduction-to-datascience/issues/103)

I summarized the comments from reviewers below. I agree that add `summarize` and `across` would be helpful, but should we cut `map` from the wrangling chapter altogether or add it and provide both approaches? 
- let me know what you think! 
- I am in favour of removing it altogether but this means we would also have to remove it from the lectures + worksheets/tutorials -- so I wanted to discuss before changing anything
- 
# Reviewer E: 
- In my experience, purrr seems to confuse newer users, so it may be worth striving to cut this section and using the new dplyr approaches instead. 

# reviewer A: 
p71: purrr is very useful, but you could also use summarize + across to achieve the type of iteration you're discussing. I'm not sure which is easier, but I thought I would mention it.

# Reviewer C: 
Section 3.7: Does this have to be introduced now? ‘map’ is hard, and readers might have a better time with it if they’ve had more practice with R before tackling it.

**Comment by trevorcampbell** [comment]
@ttimbers @leem44 I think we have now included summarize+across in wrangling, but we're keeping map too. I like that solution. Can we close this issue?

**Comment by leem44** [comment]
Yes I think we can close this now!
