### ISSUE TITLE
Feedback on "Multicollinearity and outliers" section in linear regression section

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#195]
- [ ] The first paragraph uses terms we have not used in the book before (outliers and collinear predictors) without defining them. Could we roughly hint at what they are here, or say that we will explain them, and their impact below?
- [ ] At the end of the outlier section, can we point to resources where the can read more about this in case they are interested or have to deal with this?
- [ ] In the outlier section, should we discuss the simple solution of dropping outliers? Why this can work sometimes, and why sometimes this should be avoided and instead other advanced methods (like median or quantile regression, should be used?)
- [ ] What do unstable coefficients mean, we should explain this term.
- [ ] We say "Therefore, when performing multivariate linear regression, it is important to avoid including very linearly related predictors." but this begs the question how do we avoid this? Could we suggest or show some simple ways of looking at this? And then what to do if they see this? For example, in the case of the two measurements, you could drop one, or you could create a new feature from these two where you average them?
- [ ] At the end of the multicollinearity section, can we point to resources where the can read more about this in case they are interested or have to deal with this in a more complex case than we present?

**Comment by trevorcampbell** [comment]
Need to fix this before CRC subm.
