### ISSUE TITLE
Feedback on "Designing new predictors"

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#196]
- [ ] We write "For example, a dataframe df with two variables—x and y—with a nonlinear relationship between the two variables will not be correctly captured by simple linear regression, as shown in Figure 9.11. " but is "correct" the right word? Maybe "fully" might be better?
- [ ] Can we make it clear that we drop X, when we add Z to the model?
- [ ] Should we use captitals to refer to X, Y and Z here?
- [ ] what is `df`, we never define it... 
- [ ] At the end of this section, can we point to resources where the can read more about this in case they are interested or have to deal with this in a more complex case than we present?

**Comment by trevorcampbell** [comment]
Need to handle this one before CRC subm
