### ISSUE TITLE
Chapter 1 future improvements

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#20]
- actually use `select` and `filter` when creating the plot (more convincing/motivating) and showing the code from nachos to cheesecake 

Above has been done for filter.

**Comment by ttimbers** [comment]
Reopening as I have some future thoughts:

1. Should we have sections that address everything in the learning objectives? Typically my answer is yes, however we have a lot of scaffolding/explanations in the worksheet for this chapter, and given this is a pre-reading before the first lecture I don't anticipate all people reading this before the worksheet, so the worksheet needs to stand alone. And I worry about the chapter being super redundant with the worksheet if we add a lot more... 

2. How do we link to the worksheets and tutorials? I am thinking of putting links to them at the end of each chapter? Also, with the link, a reminder to UBC students that they should be accessing their worksheets & tutorials via Canvas...

**Comment by trevorcampbell** [comment]
@ttimbers I think this is all handled now in v0.5.0?

**Comment by ttimbers** [comment]
Now we instead use `mutate` in nachos to cheesecake, but I think its fine.
