### ISSUE TITLE
maybe revisit forward selection pseudocode steps

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#208]
perhaps revisit the pseudocode steps when we first introduce forward selection. I've tried to clarify, but ultimately it is quite difficult to describe the algorithm without any use of symbols (lots of "temporary things" to keep track of)

**Comment by ttimbers** [comment]
What about a diagram? We use these for splitting and CV, so maybe that might be helpful here too?

**Comment by trevorcampbell** [comment]
I think that's a good idea. But if we do that, we should do a similar graphic for best subset selection too for consistency's sake
