### ISSUE TITLE
regression problem vs method

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#209]
From @ttimbers in #146 , regarding the beginning of Regression I:

> In the paragraph below, we start off saying "Regression [...] is a predictive problem setting ...", but it's not. First, it is not a problem setting, it's a method. Second, it is a method that can be used to predict numerical values, as well as a method that can also be used for inferential questions. So we should rephrase this sentence to reflect that.
> 
> In the paragraph below, change this sentence as suggested below:
> 
> "Both of these response variables---race time and sale price---are
> numerical, and so predicting them given past data is considered a regression problem." >
> "Both of these response variables---race time and sale price---are
> numerical, and so there are many possible values that the predictions could reasonably take on (i.e., there is not a small number of discrete categories that could possibly be predicted). This makes regression a suitable method for predicting them."

I disagree, so I'm opening an issue here to discuss rather than blocking the PR.

Worth noting that the classification section follows the same pattern.

**Comment by ttimbers** [comment]
Can you please elaborate on what you disagree on? Parts? All of it?

**Comment by trevorcampbell** [comment]
Well, the first paragraph -- which then implies that I don't think the second change is necessary.

We refer to a "classification problem" -- the problem of classifying or categorizing objects 

What is the similar "X problem" for regression? I guess I don't feel super strongly about saying "regression problem",  but more that the beginning of the chapter should focus on the problem first (not the solution). This is how the classification chapters are written, and I'd like to mirror that in the regression chapters.

**Comment by trevorcampbell** [comment]
Closing this as part of my summer 2023 cleanup. If someone feels strongly enough about this to rewrite the opening of classification 1 and regression 1 and edit any other occurrences in classification 2/regression 2 / elsewhere, I'm happy to review a PR on it, but I'm happy with it as-is.
