### ISSUE TITLE
RMSPE/RMPSE  

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#225]
We sometimes use RM**PS**E in certain places instead of RM**SP**E: 
8.6: 
- "A key feature of the formula for **RMPSE** is the squared difference between the observed target/response variable value..."

9.5
- Its used in a couple of places in 9.5

**Comment by trevorcampbell** [comment]
It should always be RMSPE. Adding this to the formatting pass.
