### ISSUE TITLE
Hyperparameters /parameters

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#229]
Adding this from https://github.com/UBC-DSCI/introduction-to-datascience/issues/93
> ### Tiffany's suggested improvements from reading it in the 2021 spring:
> * In the overview we refer to the things we are tuning in this chapter as model parameters, however, I think technically we are tuning model hyperparameters...

**Comment by trevorcampbell** [comment]
I don't think we currently make a distinction (and don't think we should)

**Comment by trevorcampbell** [comment]
(closing due to the above; but feel free to re-open if you still think we should discuss)
