### ISSUE TITLE
precision/recall

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#230]
From Reviewer A #107 Classification_continued chapter:
- "precision and recall, not discussed": Why not?"precision and recall, not discussed": Why not?

**Comment by trevorcampbell** [comment]
they are mentioned in Ch 6 in evaluation / tuning, but we don't go into any detail. 

We *could* go into a bit of detail when we introduce the confusion matrix.

**Comment by trevorcampbell** [comment]
I'm going to make this a desired enhancement for v2 -- to cover precision/recall briefly where we introduce confusion matrices

**Comment by trevorcampbell** [comment]
closing -- merging this into #470
