### ISSUE TITLE
 formatting: figures centered or left aligned 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#233]
Some figures and figure captions are centered while others are left aligned. e.g. "Figure 6.6: Plot of accuracy estimate versus number of neighbors for many K values" and "Figure 6.7: Effect of K in overfitting and underfitting" in classification II. 

- we should be consistent and do one or the other

**Comment by trevorcampbell** [comment]
added to readme (center all figs)
