### ISSUE TITLE
Chapter 2 future improvements

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#24]
- more explanation of why we should care about databases (can take from worksheet 02 / tut 02)
- add URL links to the different database types in 2.6 when introduced
- more explanation of difference between dbplyr wrangling and collect followed by wrangling, i.e., you can do lots with large data in databases without having to bring huge amounts of data to your comp

**Comment by Lourenzutti** [comment]
Hi @ttimbers and @trevorcampbell,

this comment is for Section 2.6.

I think it reads quite well. But there are two things we can think about this, the first part is the connecting to a specific database part. This will be different for different DBMS. Then there's the data wrangling and R functions that can be used when we have this connection. This will be the same independently for what is the underlying DBMS. 

I think this point might be clearer if you separate these two stages in your discussion. Something like "Section 2.6.1 Connecting to a database"  then you show how to connect to a SQLite using RSQLite and to Postgres using RPostgres(). Then, you show the examples you have for each database. the data wrangling and listing tables and so on. In this stages the functions will be the same whatever is the DBMS.
