### ISSUE TITLE
Formatting of $K$ 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#240]
I agree with this change in general. But I have noticed in the HTML navigation table that appears on the left, the $K$ symbol is really, really small.

My guess is that the PDF output looks fine, but we should check it.

I am not sure this is an issue we should fix, since it seems to be a problem with how rbookdown renders math in the navigation pane.

_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/pull/234#discussion_r713572639_

**Comment by trevorcampbell** [comment]
After looking through it all again, I think actually formatting without $ signs is probably best (it looks fine and doesn't cause that weird navigation pane issue).

The style guide in `makeindex` branch says to use $ though, so we should make a call on this and then edit the style guide if necessary.

**Comment by trevorcampbell** [comment]
OK - per discussion on slack, we have decided to go with "K-nearest neighbors", "K-NN", and "K-means" (no dollar signs). Will close this when the PR #238 merges.
