### ISSUE TITLE
Formatting 3D scatterplots 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#241]
this scatter is so incredibly cool. well done.

you should make an issue to remind us to somehow deal with this for the PDF output though (since we obviously can't do interactive 3D, so need to modify both the figure and the text after it)

_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/pull/234#discussion_r713582305_

**Comment by trevorcampbell** [comment]
added to style guide
