### ISSUE TITLE
For loop in classification chapter

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#242]
This code block has a for loop in it. Tiffany said she would make a package for fwd selection, and we should definitely make sure to do that. Might want to ping her to do that and then edit this PR accordingly.

_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/pull/234#discussion_r713598251_

**Comment by trevorcampbell** [comment]
Duplicate of #148
