### ISSUE TITLE
Formatting references printing year twice

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#243]
There's something weird about how this is rendering. I see this on the rendered page:

"Stanford Health Care. 2021. “What Is Cancer?” 2021. https://stanfordhealthcare.org/medical-conditions/cancer/cancer.html."

2021 is printed twice...

_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/pull/234#discussion_r713487185_

**Comment by leem44** [comment]
This occurs with a couple of the references so we should go through and check all of them

**Comment by trevorcampbell** [comment]
@leem44 I'll bet it's because there are `@online` bibtex entries, which isn't standard. In the `makeindex` branch I had to convert these to `@misc`. Let me see whether the issue is fixed in that branch.

**Comment by trevorcampbell** [comment]
I also noticed that the PDF bibliography output is really incomplete.

**Comment by trevorcampbell** [comment]
This is no longer happening in either the PDF or HTML copy.
