### ISSUE TITLE
Improvements for version 2 

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#251]
@trevorcampbell @leem44 - FYI, I am creating an issue here, for improvements that are beyond the scope of version 1. So when we eventually start on version two (after a long holiday from this book 🌴 🍹 ) we can easily find these here:

## Clustering
- add a section that illustrates that clustering doesn't always work in practice.

**Comment by ttimbers** [comment]
## Classification I
- including multiclass classification in Classification I - but in the scope that we put a paragraph at the end (or somewhere else) without actually exploring it at all. Discussion in closed issue #163

**Comment by ttimbers** [comment]
## Viz

- Move the section on Explaining the Visualization to its own chapter and expand and elaborated upon more

**Comment by trevorcampbell** [comment]
I moved these into their own issues (everything is a v2 improvement now, may as well keep them separate for easier search).
