### ISSUE TITLE
Chapter 3 issues (for v2)

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#254]
I've found some issues as I work through adding an index to chapter 3 and editing writing. I've left these out of my pass because I think they'd require big enough changes that discussion is warranted.

Also, I vote we leave these for version 2 of the book -- nothing is broken / incorrect here, just improvements we could make.

#### Named vectors?

When we introduce vectors in Ch 3, it seems to imply that vectors have names (because the column name is included). A few of my students in class actually had this confusion.

I am not 100% certain about R, but in other languages vectors/lists are not named. I imagine the data frame object stores the names of each column separately.

#### Paragraph before vector/list section

There is a little paragraph before the sections on vectors/lists that say that R stores dataframes with columns being lists or vectors. I don't know how useful that is given that we haven't introduced those things yet (and the forward reference to the two upcoming sections is something we tried to remove before too).

#### Visualization

It's just out of place and not at the right level of hierarchy. Why is it a subsection of the mutate section of the chapter? 

I will leave it for now though because it isn't the end of the world that it's there. Just odd.

**Comment by ttimbers** [comment]
>I am not 100% certain about R, but in other languages vectors/lists are not named. I imagine the data frame object stores the names of each column separately.

In R, both lists and vectors can have names.

**Comment by ttimbers** [comment]
We also removed the visualization.

**Comment by trevorcampbell** [comment]
Looked this over a few years later -- it's now fine. Closing
