### ISSUE TITLE
Reintroduce bar plot in chapter 3?

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#257]
There was a bar plot in chapter 3 that didn't seem to fit anywhere. So for now it's commented out in one of the `mutate` subsections (where it was originally). But we should discuss here whether it could be reintroduced in the chapter. My vote (prior to discussion) is just to leave it out.

**Comment by ttimbers** [comment]
I agree - the viz chapter is FULL.

**Comment by trevorcampbell** [comment]
great! will leave out
