### ISSUE TITLE
Numbers in the table figures in Ch 3?

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#258]
From @leem44 in a PR review, regarding the table doodles that show how the different pivot / summarize / etc functions operate.

>  I think it would help to add numbers to this table. And then you can use the example given in the paragraph above as part of this picture. e.g. with just 5 number or something find the mean or max or something.

> I could see how the cartoons would work nicely if they were used side by side to compare the concepts so students can see how each of the functions differ. But I don't know if they work without more context when introducing it as the first intro to a new concept

I am punting this possibility to version 2 of the book. But I'm not actually sure we should do this. There is something nice and simple about the examples with no numbers, and adding numbers might distract from the overall high level idea of how these functions work. Not sure though.

**Comment by leem44** [comment]
I see the value of them without the numbers too, but I think the placement of them would be better if we weren't using it as a first introduction to each concept. I think these (without numbers) would be super valuable if we put them side by side (or one after another) to compare the differences between the functions. But without more context, where it currently sits an introduction to summarizing or the map it might be difficult for readers to grasp
