### ISSUE TITLE
map_dfr vs map_dfc vs map_df

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#262]
Our textbook is quite unclear about the distinction between these. Honestly, I'm not sure I understand what the difference is. Worse, there is a bug in dplyr at the moment that makes them equivalent when they should not be.

My vote is that we either:
- include both `map_df`, `map_dfr`, `map_dfc`, clearly explain the difference between them (assuming the dplyr bug will be fixed soon), and suggest to students that they stick with one of them in this course (which one??)
- only include `map_df`, which is the one we want.

**Comment by ttimbers** [comment]
We went with `map_dfr` which `map_df` is mapped to, and we have been using in the past. We explain only `map_dfr` and `map_dfc` in the table. We don't include `map_df` because it's not in the docs and so students won't be able to look it up.

Can I close?

**Comment by ttimbers** [comment]
I think we did the best we can, so closing.
