### ISSUE TITLE
Chapter 3 future improvements

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#27]
- Add example on `mutate`? Currently this shows up in the worksheets before this week however (which is fine as it's explained when introduced there). So maybe it's better in chapter 1?

**Comment by dalimohd** [comment]
Add an example on `spread` as tutorial_03 and class activities use it.

**Comment by leem44** [comment]
- change to gather and spread to pivot_longer, pivot_wider
- change US datasets to Canadian context
- emphasize that the question being asked dictates if you need to make something wider or longer to tidy it

**Comment by leem44** [comment]
done
