### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#272]
- the bibliography is in really bad shape.
    - has some funny entries. e.g. "Canada, S. 2016"
    - bad/inconsistent capitalization
    - inconsistent journal / publisher / etc style
    - inconsistent inclusion of addresses / isbns etc
- the index is also silly. i'm not sure what generated this but it either needs to be fleshed out more (I would prefer that) or removed entirely.

_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/issues/112#issuecomment-808962967_

**Comment by trevorcampbell** [comment]
> the index is also silly. i'm not sure what generated this but it either needs to be fleshed out more (I would prefer that) or removed entirely.

I'm not sure what I was referencing there... *I* made the index. Must have been talking about something else?

**Comment by trevorcampbell** [comment]
I'm going to tag this one a bug just to force us to go through the bib before we do the final submission to CRC

In particular our bib file should follow the guide here: https://trevorcampbell.me/html/bibtex.html
