### ISSUE TITLE
Legend has "Officia" in viz

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#286]
In the plot where we make the legend horizontal, it says "Officia" instead of "Official languages"

This applies to Fig 4.14 and 4.16

Note: this is for html version

Note: it's also in the PDF version!

**Comment by ttimbers** [comment]
Duplicate of #312 and fixed in e4c160f

**Comment by trevorcampbell** [comment]
Fixed in #344
