### ISSUE TITLE
Escape pipe in index

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#308]
This needs to be fixed in wrangling:

<img width="820" alt="Screen Shot 2021-10-07 at 10 13 50 PM" src="https://user-images.githubusercontent.com/6865016/136502048-09ac5c94-3e34-47c4-ab4c-243cfd48d4c1.png">

**Comment by trevorcampbell** [comment]
The first introduction of the pipe `\index{pipesymb@\texttt{|>}}` is broken too!
