### ISSUE TITLE
Standard size for scatter and line plots?

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#310]
We should come up with a standard size for the scatter and line plots we generate, not the panel ones, but stand alone?

**Comment by trevorcampbell** [comment]
Agreed. Once you pick a reasonable setting, please add it to the style guide!

**Comment by trevorcampbell** [comment]
Also standard theme/background colour too!

**Comment by trevorcampbell** [comment]
@leem44 this one is done, right?

**Comment by leem44** [comment]
Yes this is done now!
