### ISSUE TITLE
Legends in viz chapter 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#312]
Fig 4.16 and 4.14 the legend is cut off 
<img width="708" alt="Screen Shot 2021-10-08 at 1 17 30 PM" src="https://user-images.githubusercontent.com/3838091/136620398-62c112ce-a324-4b7b-8fd8-d238983be6ed.png"
<img width="722" alt="Screen Shot 2021-10-08 at 1 17 20 PM" src="https://user-images.githubusercontent.com/3838091/136620411-f2f6169e-e6a3-429a-8c18-4e2c19802aa5.png">
>

**Comment by ttimbers** [comment]
OK, I think that means we will need to place the legend stacked vertically above the plot with:

```
theme(legend.position = "top",
        legend.direction = "vertical")
```

Which will look like: 

<img width="496" alt="Screen Shot 2021-10-19 at 11 59 52 AM" src="https://user-images.githubusercontent.com/6865016/137973939-a2cd285a-080c-4880-96ec-b85518092832.png">

I think this is the best we can do without adding too much complexity...
