### ISSUE TITLE
index "data science definition" is on the wrong page 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#314]

**Comment by leem44** [comment]
the page number in the index says the wrong page

**Comment by trevorcampbell** [comment]
This can probably be fixed by moving the `\index{...}` command closer to the actual word. I occasionally put it nearby but perhaps not close enough when I went through and made the index.

**Comment by trevorcampbell** [comment]
It's a bug in tinytex -- see the bookdown repo issue -- I've documented where the problem is.

I think the best solution for us (unless the rstudio folks move quickly) is to edit our dockerfile to install a hacked version of tinytex that runs the latex build twice before makeindex.

**Comment by trevorcampbell** [comment]
The `tinytex` devs actually handled this immediately. But to avoid depending on an unstable release of tinytex, I still suggest we hack our own version of it explicitly in the dockerfile when we install 0.34

**Comment by trevorcampbell** [comment]
Handled in #423
