### ISSUE TITLE
list is cut by figure

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#322]
list is cut in half by a figure in classification II 
<img width="715" alt="Screen Shot 2021-10-08 at 4 15 56 PM" src="https://user-images.githubusercontent.com/3838091/136633778-1811322d-a8aa-4be3-a34a-2b92cd98d381.png">

**Comment by ttimbers** [comment]
Yihui suggests this (from https://yihui.org/en/2013/06/tips-for-writing-an-r-book/):

```
\renewcommand{\textfraction}{0.05}
\renewcommand{\topfraction}{0.8}
\renewcommand{\bottomfraction}{0.8}
\renewcommand{\floatpagefraction}{0.75}
```

**Comment by ttimbers** [comment]
For figures, it seems this will help them float better:

1. In the YAML frontmatter in `pdf/index.Rmd`:

  ```
  header-includes: 
  - \usepackage{float}
  ```

2. In a code chunk in  `pdf/index.Rmd`:
  
  ```
  knitr::opts_chunk$set(fig.pos = "H",
                      out.extra = "")
  ```

For tables, it seems we need to use the `kableExtra` package and do this when we create the tables:

```
library(kableExtra)

kable(data_frame, 
      caption = "Some caption") |>
  kable_styling(latex_options = "hold_position")
```
