### ISSUE TITLE
Figures in wrangling 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#334]
Formatting of these tables looks weird since one is so much smaller than the other 
<img width="408" alt="Screen Shot 2021-10-09 at 3 30 32 PM" src="https://user-images.githubusercontent.com/3838091/136675236-143f4d67-8335-471f-8748-2b9c94fc34b1.png">

Lots of whitespace in a couple of these figures: 
<img width="379" alt="Screen Shot 2021-10-09 at 3 31 25 PM" src="https://user-images.githubusercontent.com/3838091/136675248-3bb067e2-5136-481a-bdce-702861a62ff2.png">

**Comment by ttimbers** [comment]
Solution is to regenerate figs so they are all the same size, and remove the whitespace by using `magick`'s `image_read` and `image_crop` functions to remove whitespace (in-place of `knitr`'s `include_graphics`).
