### ISSUE TITLE
Icons missing in jupyter chapter 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#336]
A couple of the icons in the chapter are missing e.g.
<img width="651" alt="Screen Shot 2021-10-09 at 3 45 27 PM" src="https://user-images.githubusercontent.com/3838091/136675505-0005a5ed-0777-4610-9c6a-012f90a71f96.png">

**Comment by trevorcampbell** [comment]
#342 closed this
