### ISSUE TITLE
Table in wrangling

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#337]
<img width="672" alt="Screen Shot 2021-10-10 at 12 57 03 PM" src="https://user-images.githubusercontent.com/3838091/136978077-1376b9f5-570c-4344-b733-d55a5643d502.png">
<img width="668" alt="Screen Shot 2021-10-10 at 12 57 23 PM" src="https://user-images.githubusercontent.com/3838091/136978334-4f05059d-5cfb-4bec-b291-dfa032558db2.png">

-	Title of column should match the case in table ("Incorporate" vs. "incorporated")
-	The writing in the paragraph no longer matches the picture since the picture includes a third column

**Comment by trevorcampbell** [comment]
#339 closed this
