### ISSUE TITLE
Add figure captions

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#36]
For all the figures in the book, we should set the `fig.cap = "....."` chunk option to add captions to figures. Some figures have captions just hanging around in the nearby text.

**Comment by leem44** [comment]
[] index
[] ch1
[] ch2 
[] ch3 
[] ch4 
[] ch5 
[] ch6
[] ch7 
[] ch8 
[] ch9 
[] ch10
[] ch11

**Comment by ttimbers** [comment]
I think this is now done except for chapter 4, which we decided it special because it has a bizillion screenshots, so closing this now.
