### ISSUE TITLE
Suggestion: Add license to rendered version of book

### ISSUE THREAD

**Issue by anelda** [UBC-DSCI/introduction-to-datascience#377]
Hallo!

Thank you so much all the work you've done to create this wonderful book!

I was just looking at the website - https://ubc-dsci.github.io/introduction-to-datascience/ - to see what license the book is made available under, and couldn't find that information easily. The information is available in the Github repo in the license file, but not everyone looking at the book, may know how to find it there and they may have questions about how they can use the book in terms of its licensing as well.

It may be worth adding the licensing explicitly to the Preface or even in its own section to make sure people can find it easily and comply.

Thanks!

Anelda

**Comment by ttimbers** [comment]
Thanks @anelda for this very good suggestion! We will do this!

**Comment by trevorcampbell** [comment]
Before we do this, we need to check our contract with CRC press to make sure that there aren't any relevant differences in the PDF and HTML/github copies of the book.

**Comment by trevorcampbell** [comment]
This was added to the landing page quite a while ago now -- closing!
