### ISSUE TITLE
Feedback to address in v1 from @RohanAlexander

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#379]
- [x] There are only two pages of citations. While possible this really is all 
the material that the authors draw on, it might be that some R 
packages are inadvertently not being cited, and that the decision to 
include links to books in footnotes, rather than as citations (e.g. p. 122 
but other places also) is artificially reducing the number of citations.
- [x] The phrase ‘scientific disciplines’ or ‘applications’ is used on p. 277 and
p. 327 seemed unusual to me and I didn’t understand what ‘scientific’ 
was meant to refer to?
- [x] p. 25: `filter` 
- [x] p. 48: Odd spacing between ‘.csv’ and ‘file’.
- [x] p. 51 (and elsewhere in footnotes): Odd links that don’t work.
- [x] p. 59: ‘chapter 3’, instead of ‘Chapter 3’.
- [x] p. 65 ‘Tidyverse twitter’ instead of ‘Tidyverse Twitter’.
- [x] Generally, some inconsistency about ‘tidyverse’ or ‘Tidyverse’ throughout.
- [x] p. 109: ‘the data set the no’ instead of ‘the data set that no’.
- [x] p. 110: ‘see that no longer’ instead of ‘we see that we no longer’.
- [x] p. 114: missing paragraph spacing before ‘Note that...’?
- [x] p. 175: odd spacing in the two bullet points at the end.
- [x] p. 194: overfull line extending over the edge of the page.
- [x] p. 303: ‘help make our’ instead of ‘help make sure our’

**Comment by trevorcampbell** [comment]
addressing these in the `rohan-edits` branch

**Comment by trevorcampbell** [comment]
Moving checking footnotes into its own issue because it's a global pass thing
