### ISSUE TITLE
Clustering chapter todos

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#38]
- arrow pointing from "Elbow" label on figure to actual elbow point

**Comment by trevorcampbell** [comment]
From Petal:
- Section 10.3
"While at first glance, clustering may seem very similar to classification, these two methods have some very important distinction" --> "... distinctions"
- Section 10.3.1
The blue/green clusters seem to be reversed
- Might want to keep naming consistent (K-means versus Kmeans)
- One of the learning objectives is identifying the need to scale variables, but there is no mention of scaling within the chapter

**Comment by ttimbers** [comment]
Added arrow pointing to elbow in 920069f6f

**Comment by ttimbers** [comment]
> Section 10.3.1: The blue/green clusters seem to be reversed

Fixed in 2bb1f0d9ae2a

> "While at first glance, clustering may seem very similar to classification, these two methods have some very important distinction" --> "... distinctions"

Is no longer present in the chapter, so skipping.

> Might want to keep naming consistent (K-means versus Kmeans)

Moved chapter text to "K-means" instead of a mix of the two in 904eee1180401

> One of the learning objectives is identifying the need to scale variables, but there is no mention of scaling within the chapter

Added section here d05f69a12c. Would eventually like to redo this chapter with data that needs to be scaled data. However, I guess they see that in the tutorial...

**Comment by trevorcampbell** [comment]
@ttimbers we can close this one now that #78 was merged, right?

**Comment by ttimbers** [comment]
Yup!
