### ISSUE TITLE
Copyedit items left as-is

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#381]
# Intro 
- Figure 1.7, 1.8 says to fix labels, but labels are purposely bad

**Comment by trevorcampbell** [comment]
The black line at the bottom of the note box that starts section 6.8 is placed on the next page. 

Other edits will almost certainly change where latex puts this, so I'm not going to worry about it until content is settled and we deal with other latex spacing issues (e.g. #395 )

**Comment by trevorcampbell** [comment]
These have all been dealt with now. Closing!
