### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#382]
Replace the hyphen with an en dash, with no space around the dash, in all number ranges throughout the book.

e.g. see comment in preface for example

**Comment by trevorcampbell** [comment]
use &ndash; for en-dashes (number ranges) -- e.g., "the speed fell in the range 50km/h&ndash;60km/h"

use &mdash; for em-dashes (parenthetical statements) -- e.g., "the boat&mdash;which was yellow&mdash;was fast"
