### ISSUE TITLE
reading chapter active text margin

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#385]
on pg 59: need to move the text within the active text margin.
<img width="423" alt="Screen Shot 2021-12-03 at 4 21 02 PM" src="https://user-images.githubusercontent.com/3838091/144688764-c5433167-5bfd-43ed-b45c-40aede961c5e.png">

**Comment by ttimbers** [comment]
Can you please add a screen shot of this for easy ref?

**Comment by trevorcampbell** [comment]
Done as of d10e86a
