### ISSUE TITLE
Problem with a link in section 1.2 Jupyter notebooks

### ISSUE THREAD

**Issue by luifrancgom** [UBC-DSCI/introduction-to-datascience#39]
Hello 

In "1 Introduction to Data Science > 1.2 Jupyter notebooks" the link "Here is a worksheet" doesn´t work

**Comment by ttimbers** [comment]
Thanks for flagging this bug! For now you can find them here: https://github.com/UBC-DSCI/dsci-100-assets/tree/master/2019-fall/materials (look at the worksheets before the tutorials).

**Comment by trevorcampbell** [comment]
Fixed this in dad77bc but opening a new issue #40  to go over whole textbook to check for links
