### ISSUE TITLE
Lots of empty whitespace (due to figs)

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#395]
As I've gone through and worked on the copy editor's comments, I've noticed that we have many large chunks of whitespace in the text. This is due to figure placement / LaTeX trying to avoid awkward paragraph breaks / etc. We should get help from CRC to minimize these once all the content edits are done.

**Comment by ttimbers** [comment]
Working on the figure whitespace issue. From CRC Press, the advice was to not use global fixed figure positions (i.e., let them float) and then when figures are silly (show up in the middle of code chunks or output) use `fig.pos = "H"` to fix just those figures.

So now that all other changes are done. I am rebuilding the PDF without fixed figure positions (letting them float) and then I will identify the ones that need to be fixed, and then fix them. I think this might need to be done one-by-one, as each figure fixing may impact follow-on figures (at least within a chapter).

**Comment by trevorcampbell** [comment]
Done as of d10e86a
