### ISSUE TITLE
remove pdf/epub download and "Edit" from toolbar

### ISSUE THREAD

**Issue by lheagy** [UBC-DSCI/introduction-to-datascience#417]
Currently, the links for the pdf / epub from the toolbar lead to a "Page not found" 

- pdf: https://ubc-dsci.github.io/introduction-to-datascience/_main.pdf
- epub: https://ubc-dsci.github.io/introduction-to-datascience/_main.epub

Should these be available to download? or should we disable the download links to avoid confusion?

**Comment by trevorcampbell** [comment]
These aren't (and can't, I believe, for contractual reasons) be available. 

We should definitely disable these links in the HTML render if we can!

**Comment by trevorcampbell** [comment]
Related: the "edit" button in the toolbar points here to a broken URL: https://github.com/rstudio/bookdown-demo/edit/master/index.Rmd

**Comment by trevorcampbell** [comment]
I think the `index.Rmd` example on the following page shows how to disable it, not sure if it gets removed entirely:

https://bookdown.org/yihui/bookdown/html.html

testing now

**Comment by trevorcampbell** [comment]
OK, PR opened #418

**Comment by lheagy** [comment]
Thanks @trevorcampbell!

**Comment by trevorcampbell** [comment]
Done as of d10e86a
