### ISSUE TITLE
Change verbiage and link in exercise section

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#421]
Currently the exercise section links directly to the worksheet on GitHub, but skips over the landing page where they can use binder. We were going to change this, but missed doing this. Here's what it currently says:

"Exercises
Practice exercises for the material covered in this chapter can be found in the accompanying worksheet. The worksheet tries to provide automated feedback and help guide you through the problems. To make sure this functionality works as intended, please follow the instructions for computer setup needed to run the worksheets found in Chapter 13."

I think we wanted to add a link to the table with the worksheets and Binderhub links to each of these....

**Comment by trevorcampbell** [comment]
Handled in #423
