### ISSUE TITLE
Position/order of note and warning in reading chapter

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#436]
The warning line from `read_csv` should come before the Note... but it's not for some reason... (page 33 of book, source is in `reading.Rmd`)

<img width="710" alt="Screen Shot 2022-05-04 at 8 20 09 PM" src="https://user-images.githubusercontent.com/6865016/166864967-0049ee91-7251-465c-8289-93b17ffa90ee.png">

(same issue is present in html version of book...)

Source: 

<img width="981" alt="Screen Shot 2022-05-04 at 8 21 28 PM" src="https://user-images.githubusercontent.com/6865016/166864996-ca19c830-ce02-4927-b615-2138181011aa.png">

This appears to be a `bookdown` thing... because if instead I use the knit button (or `rmarkdown::render`) it does what you would expect:

<img width="612" alt="Screen Shot 2022-05-04 at 8 30 37 PM" src="https://user-images.githubusercontent.com/6865016/166865055-1c671bdc-13dc-40a6-b7c6-1c8f6f5095d4.png">

**Comment by trevorcampbell** [comment]
@ttimbers did we file an issue with bookdown? If so, we should link that here so it's easy to keep track of
