### ISSUE TITLE
Colors for images

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#438]
When the book goes to print with T&F, the color used will be CMYK. However, we have created the book using RGB. This causes some figures to look less than ideal in print (see example below). When attempting version 2 (or adding any new plots or images to the book) we should revisit the colors to make sure they work in both color schemes. 

For example, here is the path figure in PDF using RGB:

<img width="400" alt="pdf-authors-compile" src="https://user-images.githubusercontent.com/6865016/173133076-54bb4d26-d65c-4c7f-8cea-3f5ae897bc08.png">

And here is the same figure using CMYK:

<img width="400" alt="pdf-tf-compiles" src="https://user-images.githubusercontent.com/6865016/173133127-23710276-b1b7-44f3-936b-ce59bd73528c.png">

**Comment by trevorcampbell** [comment]
Update: we tried to do everything in CMYK, but it causes so many other issues with file formats, web rendering, etc that it's just not worth it. 

Plan now is to do everything with PNG in RGB, but manually check CMYK conversion to make sure everything will look reasonable in print too.
