### ISSUE TITLE
Section 7.5 - Clarify Stratification

### ISSUE THREAD

**Issue by HaydenMcT** [UBC-DSCI/introduction-to-datascience#44]
The discussion of Stratification in the text is brief and a little more vague than it ideally would be.

**Comment by HaydenMcT** [comment]
An additional issue: there is a common misunderstanding from the current wording in the text that stratification solves imbalance (so students are confusing it with upsampling) when the textbook in fact claims that stratification is just extra important when there is class imbalance.

**Comment by ttimbers** [comment]
@trevorcampbell - do you think our revisions addressed this?

**Comment by trevorcampbell** [comment]
From another issue on this topic:

> In the cross-validation section, we might want to give more attention to stratification (perhaps even give it its own section). I don't think this is blocking for the first version of the book, so punting to an issue.

**Comment by trevorcampbell** [comment]
@ttimbers I don't think we do cover it explicitly yet, though it is better than what we had before. I'm going to relabel this a v2 enhancement, as it isn't blocking our v1 release.

**Comment by trevorcampbell** [comment]
Few years later -- I think this is fine as-is. Closing
