### ISSUE TITLE
Matching narrative to the plot in Section 7.7 

### ISSUE THREAD

**Issue by GloriaWYY** [UBC-DSCI/introduction-to-datascience#440]
In the [Section 7.7 Underfitting and overfitting](https://github.com/UBC-DSCI/introduction-to-datascience/blob/master/regression1.Rmd#L500), the textbook says to fit a KNN regression model with `neighbors=932` (the size of the entire dataset); however, in the code, fitting was done on only the training split (size=699). It will cause an error if we really use `neighbors=932` since `neighbors` cannot be larger than the data size. (The code this error because it uses an if/else statement and does not actually fit `neighbors=932`, instead it takes [the mean of all training samples](https://github.com/UBC-DSCI/introduction-to-datascience/blob/master/regression1.Rmd#L542), which is equivalent to using `neighbors=699` where 699 is the training sample size).

**Comment by trevorcampbell** [comment]
I think this should have been closed by #452, but need double-check this

**Comment by trevorcampbell** [comment]
Yep, should have been closed -- closing now
