### ISSUE TITLE
Fig 10.9: overview of bootstrap image error

### ISSUE THREAD

**Issue by chendaniely** [UBC-DSCI/introduction-to-datascience#441]
The "Overview of the bootstrap process" image has an error where the first bootstrap sample 1 has the number `3` in it, but the sample it's bootstrapping from does not contain a `3`

![image](https://user-images.githubusercontent.com/5782147/174645412-780b7b00-a9c0-4bc2-82ca-7488dfc08bbe.png)

**Comment by trevorcampbell** [comment]
Fixed now on `master`
