### ISSUE TITLE
Textbook chapter assignments and major changes

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#45]
|Lead author | Checker |  Chapter | Key changes
|--|-- | -- | --
| ~~Tiffany~~ | ~~Melissa~~ | ~~00-intro.Rmd~~ | Re-record videos R4.0 changes ? base on Jupyter lab
| ~~Melissa~~ | ~~Tiffany~~ | ~~01-reading.Rmd~~ | ~~R4.0 changes ? (TC: I think these are done now?)~~
| ~~Melissa~~| ~~Tiffany~~ | ~~02-wrangling.Rmd~~ | ~~R4.0 changes ? (TC: I think these are done now?)~~
| ~~Tiffany~~| ~~Trevor~~ |~~03-viz.Rmd~~ | 
| ~~Tiffany~~ | ~~Trevor~~ | ~~04-version_control.Rmd~~ | ~~Record videos, written from scratch, base on Jupyter lab~~
| ~~Trevor~~ | ~~Tiffany~~ | ~~05-classification.Rmd~~ | ~~move to tidymodels~~
| ~~Trevor~~ | ~~Tiffany~~ | ~~06-classification_continued.Rmd~~ | ~~move to tidymodels~~
| ~~Trevor~~ | ~~Melissa~~ | ~~07-regression1.Rmd~~ | ~~move to tidymodels~~
| ~~Trevor~~ | ~~Melissa~~ | ~~08-regression2.Rmd~~ | ~~move to tidymodels~~
| Tiffany | Melissa | 09-clustering.Rmd |
| ~~<s> Melissa~~ | ~~<s> Trevor~~  |~~<s>  10-inference.Rmd~~ |~~<s>  written from scratch ~~
| ~~Tiffany~~ | ~~Trevor~~ | ~~11-moving-to-your-own-machine.Rmd~~ | ~~written from scratch~~

## Workflow
- Work in a Docker image ~~(write a dockerfile for this - [rocker/verse base](https://hub.docker.com/r/rocker/verse) - need to upgrade to 4.0)~~
- brach `dev` off of `master`
- branch all new edits off `dev`, merge back to `dev`
- merge `dev` into `master` for September 1, 2020

## Tidymodels resources
- https://juliasilge.com/blog/supervised-ml-course/
- https://alison.rbind.io/talk/2020-cascadiarconf-tidyml/
 
## Major things to do:
- ~~images, remake or get permissions (Melissa)~~
- re-record the videos (Tiffany)
- run [`stylr`](https://www.tidyverse.org/blog/2017/12/styler-1.0.0/) to have consistent style (Melissa)
- read through issues relevant to textbook (Trevor)
- ~~datasets (make their harvesting reproducible, or have good citations in the text - probably both) (Trevor)~~
- cite software packages as well (Trevor)

**Comment by ttimbers** [comment]
@UBC-DSCI/dsci-100 - I ran into the first R 4.0 error today - `caret::upSample` blows up when we use `unlist` to generate the vector, not `pull`, thus we need to move to `pull` in this case... I feel like we are going to have a lot of these... At a minimum we should post them in this thread, and then also add to this issue for the worksheets and tutorials: https://github.ubc.ca/UBC-DSCI/dsci-100-instructor/issues/220

**Comment by trevorcampbell** [comment]
> datasets (make their harvesting reproducible, or have good citations in the text - probably both) (Trevor)

Regarding this -- I've created a new branch `data-reproducibility` and pushed a notebook `data/retrieve_datasets.ipynb` that obtains all data from their original source, cleans them, compares the result to a stored hash, loads a stored copy of the data and compares that to the hash too.

Remaining todos:
- properly fill out all metadata for each dataset
- make sure the new data does not break the textbook rendering
    - I had to write new code to obtain certain data, because DataUSA's API changed
- make the notebook able to handle saving data to different formats, right now it's just CSV

**Comment by trevorcampbell** [comment]
I just added a PR #55 for my major chapter edits. @leem44 and @ttimbers please review and provide feedback!

**Comment by trevorcampbell** [comment]
Tidymodels update to 6,7,8,9 done + merged into `master`!

**Comment by ttimbers** [comment]
Closing as this was the last round of reviews and this work is done.
