### ISSUE TITLE
Eloborate on how to download Jupyter content from the server

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience#458]
There were some good images and more detailed instructions in this years announcemnt that I thought mihgt be good to add to the book https://datasciencebook.ca/appendixA.html

These are the instructions to zip up your dsci-100-student folder, so you can save all the files in 1 go. Since JupyterHub doesn't let you download folders:

go to your home directory (click on that folder icon below the + symbol)

![image](https://user-images.githubusercontent.com/4560057/208278542-d02ae4bc-b813-4d60-8182-c6c3d18f479a.png)

Click the + to open up a new file and select "Terminal" under the "Other" section

![image](https://user-images.githubusercontent.com/4560057/208278548-cf6668d4-b9d0-4b06-b2a3-66839c66f842.png)

type in the following command to zip up your dsci-100-student folder into a file called dsci-100-student.zip:
zip -r dsci-100-student.zip dsci-100-student/
if you want to save everything in your home folder run: zip -r dsci-100-all.zip ~

![image](https://user-images.githubusercontent.com/4560057/208278553-f85b6d5c-c1de-499f-aa39-d6117e651034.png)

You will see a new file on the left side called dsci-100-student.zip (you might need to refresh the page) that you can download.

![image](https://user-images.githubusercontent.com/4560057/208278558-40642cdb-7907-4905-9e62-0dbe737e0951.png)

**Comment by trevorcampbell** [comment]
This stuff is kind of specific to DSCI100, and the textbook is meant for a more general audience. If we do include it we should think carefully about how (and where) best to frame/present the topic.

**Comment by trevorcampbell** [comment]
Summer update: I've now actually completely removed "getting stuff from jhub" from the book. It's just too specific to our class. 

@joelostblom I'm going to close this issue here, but feel free to re-open it in the instructor repo where maybe we can build this sort of thing into our last week of slides. :)
