### ISSUE TITLE
Runnable and executable Rmd code

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#46]
I think its great that we're using Rmd & bookdown to make our book reproducible, but it might be possible to go one step further, see these set of tutorials that use learnr to have Runnable and executable code in a Rmd-based website: https://tinystats.github.io/teacups-giraffes-and-statistics/02_bellCurve.html

Here's the tutorial how she made it (it's embedded iframes, so in theory we should be able to do this in bookdown???): http://desiree.rbind.io/post/2020/learnr-iframes/

cc @trevorcampbell

**Comment by trevorcampbell** [comment]
This is still a neat idea, but I don't think this kind of major overhaul of the book is possible at this point. Closing
