### ISSUE TITLE
Remove historical_vote_* data

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#51]
I have implemented the new data reproducibility pipeline in `retrieve_data.ipynb` in the `data-reproducibility` branch (which should soon be merged into `dev`. Currently all clean CSV datasets used in the textbook are created by running this notebook from start to finish. Some additional data conversions to different file types are generated by the `data/create_state_property_vote_variants.R` script.

However, there are a bunch of `historical_vote_*` datasets used in the wrangling chapter as examples of messy data. The `retrieve_data.ipynb` notebook generates the `us_vote.csv` data, which is the complete original version of that historical vote data. But I did not implement any script to generate the various messy `historical_*` data, because there is a plan to move away from this data anyway shortly.

Once we start moving away from that historical vote data, we should:

- delete all `historical_vote_*` files
- delete the note in the `retrieve_data.ipynb` file about the messy variants

I vote that we keep the `us_vote` block in `retrieve_data.ipynb` on the off-chance that we want to use that data in the future.

**Comment by trevorcampbell** [comment]
@ttimbers #56 and this one are now no longer relevant as we're using canlang, correct? Close?

**Comment by ttimbers** [comment]
Correct.
