### ISSUE TITLE
python packages in docker image

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#53]
Once the `dev <- docker` PR #50 is merged, we should think about adding the python packages needed for `data/retrieve_data.ipynb` to the docker image and adding instructions on how to run the notebook in a docker container.

**Comment by ttimbers** [comment]
Here's a Dockerfile that does this (pasting this here so I can add the relevant bits to our Dockerfile): https://github.com/andrie/tensorflowr/blob/master/reticulate/Dockerfile

**Comment by ttimbers** [comment]
This was addressed a while ago. Closing.
