### ISSUE TITLE
Add acknowledge to @gcohenfr 's regr-1 slides from MDS

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#544]
I think I failed to acknowledge that Figure 8.3 (shown below) was inspired from @gcohenfr 's regr-1 slides from MDS (also shown below) which I would have seen when I worked with her on that course as her lab instructor. I think we should fix this by adding an acknowledgement to the book.

Figure 8.3 in this book:

![Screenshot 2023-09-26 at 3 53 49 PM](https://github.com/UBC-DSCI/introduction-to-datascience/assets/6865016/215cb58e-e856-4014-a64a-34f0b05992a4)

@gcohenfr 's regr-1 slides from MDS:

<img width="400" alt="Screenshot 2023-09-26 at 3 55 43 PM" src="https://github.com/UBC-DSCI/introduction-to-datascience/assets/6865016/d4609527-1c8b-46d0-bfc4-c4c454d6e4ea">

**Comment by trevorcampbell** [comment]
@ttimbers can you post a public, static link to those figures from the original source you mentioned? otherwise it will be awkward to cite it

**Comment by ttimbers** [comment]
I wasn't thinking officially citing it in the text, because as you say, this slide deck is not publicly available. However, we could add this to our acknowledgements page:

> _We would like to thank Gabriela Cohen Freue for her DSCI 561 (Regression I) teaching materials in the UBC Master of Data Science program, as some of our linear regression figures were inspired from these._

**Comment by trevorcampbell** [comment]
Sounds good to me! I'll just add it to the current "bunch of small changes + scraping/API" PR

**Comment by ttimbers** [comment]
Thank-you!

**Comment by gcohenfr** [comment]
Thanks to all! My main point taking with Tiffany was that a similar presentation will be included in my book (class notes for now). In any case, happy to inspire. I’m also getting inspired with your material! Thanks!
