### ISSUE TITLE
Graphical inconsistencies

### ISSUE THREAD

**Issue by designbyjaki** [UBC-DSCI/introduction-to-datascience#548]
- some single color graphs are black, some gray in viz
- Trendlines should have a consistent color palette and width
- vertical/horizontal marker lines should have a consistent style, color, and width (dashed/dotted, etc)
- Comparison lines (linking between points and axis marker lines/trendlines) should have a consistent color and width
- Brackets should be consistent (curly braces for code block figures in ch1 e.g., square brackets elsewhere)
- left-aligned vs center-aligned (code figures are currently center-aligned, should be left)
- reading: inconsistent heading size
- code block figure fonts should be consistent
- orange and teal bars in ch4?
- ch6: different fonts between entire graphic and "test set" bit
-

**Comment by trevorcampbell** [comment]
(and they switch to blue in inference)

**Comment by trevorcampbell** [comment]
- diamonds in classification, red circles in classification
