### ISSUE TITLE
Replace US election data with Canadian language data

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#56]
@trevorcampbell @leem44 - I want to replace the US election data with something more Canadian (and less political). I have created an R package named {[canlang](https://ttimbers.github.io/canlang/)} from the Canadian census data so we can easily access it for the textbook. Here's a snippet of the data set:

``` r
library(canlang)
head(can_lang)
#>                                  category               language mother_tongue
#> 1 Non-Official & Non-Aboriginal languages              Afrikaans         10260
#> 2 Non-Official & Non-Aboriginal languages             Akan (Twi)         13460
#> 3 Non-Official & Non-Aboriginal languages               Albanian         26895
#> 4                    Aboriginal languages              Algonquin          1260
#> 5 Non-Official & Non-Aboriginal languages American Sign Language          2685
#> 6 Non-Official & Non-Aboriginal languages                Amharic         22465
#>   most_at_home most_at_work lang_known
#> 1         4785           85      23415
#> 2         5985           25      22150
#> 3        13135          345      31930
#> 4          370           40       2480
#> 5         3020         1145      21930
#> 6        12785          200      33670
```

And we can make figures similar to the ones we had in chapter one:

![README-example plot from data-1](https://user-images.githubusercontent.com/6865016/89739932-ab4a8480-da39-11ea-92d2-4cfdde01d770.png)

**Comment by trevorcampbell** [comment]
Big +1 from me on this. Aside from incorporating this into the textbook, we should make our storage / usage / processing of data sources consistent. Earlier I made a data/ folder and processing script for this purpose, but I've created a new issue #58 for the creation of a R package to handle all of our data.

**Comment by ttimbers** [comment]
first draft of this in 740815c

**Comment by trevorcampbell** [comment]
@ttimbers v0.5.0 completed this one, right?

**Comment by ttimbers** [comment]
Yup!
