### ISSUE TITLE
GitHub chapter

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#57]
For the UBC Jupyterdays I created this chapter: https://ubc-dsci.github.io/jupyterdays/sessions/timbers/sharing-materials-with-git/sharing-materials-with-git.html

Three sections of it are relevant for our GitHub chapter:
- [Creating a course repository to host materials on GitHub.com](https://ubc-dsci.github.io/jupyterdays/sessions/timbers/sharing-materials-with-git/sharing-materials-with-git.html#creating-a-course-repository-to-host-materials-on-github-com)
- [Edit and add materials in your course repository on GitHub.com](https://ubc-dsci.github.io/jupyterdays/sessions/timbers/sharing-materials-with-git/sharing-materials-with-git.html#edit-and-add-materials-in-your-course-repository-on-github-com)
- [Using JupyterHub to create & edit content, as well as send updates to GitHub.com](https://ubc-dsci.github.io/jupyterdays/sessions/timbers/sharing-materials-with-git/sharing-materials-with-git.html#using-jupyterhub-to-create-edit-content-as-well-as-send-updates-to-github-com)

> Note: the audience is different so I will edit this and take screen shots that make a more student-like project, but a lot of steps and wording can be reused.

Another section that would need to be added for us is how to deal with merge conflicts and perhaps a section on Jupytext?

**Comment by trevorcampbell** [comment]
done now as of v0.5.0
