### ISSUE TITLE
Typo in chapter 2.6.2 database connection name

### ISSUE THREAD

**Issue by chendaniely** [UBC-DSCI/introduction-to-datascience#578]
In section 2.6.2 (https://datasciencebook.ca/reading.html#reading-data-from-a-postgresql-database)

we make the database connection named `conn_mov_data` in the code, but the prose text refers to it as `can_mov_db`.

Student reported this screen shot:

![image](https://github.com/UBC-DSCI/introduction-to-datascience/assets/5782147/5924e1bd-c3f4-46cb-b737-d0dca8c42965)

**Comment by trevorcampbell** [comment]
The confusion here is that `conn_mov_data` is the connection object, while `can_mov_db` is the database.

Really the fix here is to change `conn_mov_data` to `can_mov_conn` to indicate that it's the connection to the can mov db.

**Comment by trevorcampbell** [comment]
I'll make the same change to the `conn_lang_data` as well for consistency

(after double checking it doesn't make anything else unclear)
