### ISSUE TITLE
explaining centering/scaling

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#59]
One remaining comment from PR #55 : This is just a general comment about this section: I wonder if it would be useful to give a formula here or even just show step by step how we subtract the mean and then divide by the sd in the dataset. I find students confused with what we are doing exactly when we are centering, scaling

**Comment by ttimbers** [comment]
@trevorcampbell - do you think we still need to do this?

**Comment by leem44** [comment]
I think we can close this, I think this was my comment originally -- but we improved on the explanation in the last edits and explained sd and mean etc.

**Comment by trevorcampbell** [comment]
Yup, I think it's fine now.
