### ISSUE TITLE
Scaling data - more info

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#6]
Add a slightly more detailed explanation of scaling data (including ideally a figure that shows intuition)

**Comment by trevorcampbell** [comment]
(recommend scaling + centering as well)

**Comment by ttimbers** [comment]
@trevorcampbell - is this still something we want to do at some point?

**Comment by trevorcampbell** [comment]
@ttimbers I think the new figs in the textbook where it's introduced (specifically in classification) are pretty clear on it now
