### ISSUE TITLE
Ch 3 wrangling chapter change out Edmonton

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#72]
Switch out Edmonton for a region that speaks more French (e.g. Moncton) so we can make a more interesting barplot (stacked bar chart comparing the proportion of French/English in different regions)

**Comment by ttimbers** [comment]
@leem44 - this is now just a table in wrangling. Do you think this is something we want to do for V2 or not any more given we don't make that plot?

**Comment by trevorcampbell** [comment]
I think this is fine as-is now!
