### ISSUE TITLE
Further refinements for wrangling chapter

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#74]
Talking with Jenny Bryn, she recommends that we avoid oversimplifying the differences between built-in R data frames and tibbles. She says she's seen too many issues, tweets, community posts, etc. where someone absolutely wants to believe tibbles are just data frames that print better and then they find a behaviour where that’s not true.

@trevorcampbell @leem44  - I asked her what we should point out (and to what level) and she recommended these high points:
- printing (although not true in Jupyter sadly)
- subsetting
- row names (general lack and de-emphasis of)
- grouping, list-columns, df-cols (so generalizations that are super-handy for keeping semi-complicated tasks solvable with a data-frame-y structure)
- no auto-munging of column names, no automatic factors (although R 4 itself changed this)

She said that a novice won’t be able to directly appreciate all of those things on day one, but they can be offered up as reasons why we are burdening them with a new word and concept.

**Comment by trevorcampbell** [comment]
I personally don't think we should go into more detail than we already do re: tibbles vs data.frames -- seems like just a really technical point for that early in the book.

But I do think we introduce the fact that there *exist* alternatives sort of abruptly and without any real focus. Text as it is now:

> The functions from the tidyverse package that we use often give us a special class of data frame called a tibble. Tibbles have some additional features and benefits over the built-in data frame object. These include the ability to add useful attributes (such as grouping, which we will discuss later) and more predictable type preservation when subsetting. Because a tibble is just a data frame with some added features, we will collectively refer to both built-in R data frames and tibbles as data frames in this book.

"over the built-in data frame object" -- have we even mentioned that such an object exists? I'm kind of tempted to rewrite this bit to more clearly introduce that there is a distinction, touch on differences at the level we do now, and then never mention data.frames again
