### ISSUE TITLE
Remove our actual usernames from git examples...

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#91]
I am getting a lot of github repo invites, I assume because my username is used in the examples / images relating to inviting people to repositories. We should replace those with fake account names.

**Comment by trevorcampbell** [comment]
Did this for the problematic figures. There are still a few where it displays our usernames, but not where "actions are happening" so students following along won't use our names, hopefully

**Comment by ttimbers** [comment]
@trevorcampbell - do we need to do any more with this. I am really fine with mine being in there.

**Comment by trevorcampbell** [comment]
I think it's fine now. I removed my name where it was part of the "adding a collaborator" step that caused a bunch of students who were following along to invite me to random repos.
