### ISSUE TITLE
Review timeline/workflow

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#97]
| Deadline/timeline | Task |
|----------|------|
| 2021/03/30  | Read review and open required issues |
| 2021/03/30 | Meet to decide on path for global issues & assign tasks |
| April 15 - June 5 | Complete global content tasks (commenting work done in [rebuttal.md](https://github.com/UBC-DSCI/introduction-to-datascience-reviews/blob/main/rebuttal.md)) |
| June 5 - July 7 | Complete chapter content tasks (commenting work done in [rebuttal.md](https://github.com/UBC-DSCI/introduction-to-datascience-reviews/blob/main/rebuttal.md)) |
| July 7 - August 1 | Work with CRC Press to complete the formatting tasks & Rebuttal |

**Comment by trevorcampbell** [comment]
@ttimbers @leem44 this is done now, right?

**Comment by trevorcampbell** [comment]
Closing this, we are past this planning horizon and have completed / in progress on all tasks
