### ISSUE TITLE
Chapter 10 (Clustering) bug

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#98]
In Chapter 10 (Clustering) there is a bug where we show them how to do clustering in R... We accidentally use the `label` column in our clustering... This is just there so that we can colour the points in the earlier plots and should be removed...

[Here](https://github.com/UBC-DSCI/introduction-to-datascience/blob/d74711b542b97e7d4360e9055b4c9fd7d13daca1/09-clustering.Rmd#L451) we should add a hidden code chunk that does this:

```
marketing_data <- marketing_data %>%
    select(-label)
```

cc @leem44

**Comment by trevorcampbell** [comment]
I believe this is fixed now in the new penguins version of the example
